### ISSUE TITLE
Getting 'Could not publish to topic ''

### ISSUE THREAD

**Issue by Morshed0308** [rebus-org/Rebus#1026]
Our project was running well and serviceBus was working fine with **.net 3.1**. Recently we have upgraded to **dotnet 5** . Since then serviceBus cannot publish anything and service bus is not working at all. When trying to publish any topic we get the following 

 at Rebus.AzureServiceBus.AzureServiceBusTransport.<>c__DisplayClass29_0.<<GetOutgoingMessages>b__3>d.MoveNext()\r\n--- End of stack trace from previous location ---\r\n   at Rebus.AzureServiceBus.AzureServiceBusTransport.<>c__DisplayClass29_1.<<GetOutgoingMessages>b__1>d.MoveNext()\r\n--- End of stack trace from previous location ---\r\n   at Rebus.Transport.TransactionContext.InvokeAsync(Func`1 actions)\r\n   at Rebus.Transport.TransactionContext.Complete()\r\n   at Rebus.Bus.RebusBus.InnerSend(IEnumerable`1 destinationAddresses, Message logicalMessage)\r\n   at Rebus.Bus.RebusBus.InnerPublish(String topic, Object eventMessage, IDictionary`2 optionalHeaders)\r\n   at () in .cs:line 1905\r\n   at (I) in ' '   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Logged|12_1(ControllerActionInvoker invoker)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)"

**this is my service bus integration code.**
```

 services.AddRebus((config, provider) => config
                .Logging(l => l.Use(new MSLoggerFactoryAdapter(provider.GetService<ILoggerFactory>())))
                .Serialization(s =>
                {
                    s.UseNewtonsoftJson();
                })
                .Transport(t => t
                    .UseAzureServiceBus(configuration["ConnectionStrings:ServiceBus"], "Booking")              
                )
                .Routing(r => r.AddRoutes())
                .Options(o => o
                    .AssignClaimsPrincipalIdentity(provider)
                    .AssignClaimsPrincipalPolicy(provider)
                    .LogPipeline(verbose: true)
                )
            );
```

can anyone help me with this issue? Thanks in advance.

**Comment by Morshed0308** [comment]
Thanks for your reply. @mookid8000 
are you referring to this error message?



An error occurred when attempting to receive the next message: System.InvalidOperationException: Operation is not valid due to the current state of the object.
   at Microsoft.Azure.ServiceBus.Core.MessageReceiver.OnReceiveAsync(Int32 maxMessageCount, TimeSpan serverWaitTime)
   at Microsoft.Azure.ServiceBus.Core.MessageReceiver.<>c__DisplayClass64_0.<<ReceiveAsync>b__0>d.MoveNext()
   at Microsoft.Azure.ServiceBus.Core.MessageReceiver.<>c__DisplayClass64_0.<<ReceiveAsync>b__0>d.MoveNext()
   at Microsoft.Azure.ServiceBus.Core.MessageReceiver.<>c__DisplayClass64_0.<<ReceiveAsync>b__0>d.MoveNext()
   at Microsoft.Azure.ServiceBus.Core.MessageReceiver.<>c__DisplayClass64_0.<<ReceiveAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.Azure.ServiceBus.RetryPolicy.RunOperation(Func`1 operation, TimeSpan operationTimeout)
   at Microsoft.Azure.ServiceBus.RetryPolicy.RunOperation(Func`1 operation, TimeSpan operationTimeout)
   at Microsoft.Azure.ServiceBus.RetryPolicy.RunOperation(Func`1 operation, TimeSpan operationTimeout)
   at Microsoft.Azure.ServiceBus.RetryPolicy.RunOperation(Func`1 operation, TimeSpan operationTimeout)
   at Microsoft.Azure.ServiceBus.Core.MessageReceiver.ReceiveAsync(Int32 maxMessageCount, TimeSpan operationTimeout)
   at Microsoft.Azure.ServiceBus.Core.MessageReceiver.ReceiveAsync(Int32 maxMessageCount, TimeSpan operationTimeout)
   at Microsoft.Azure.ServiceBus.Core.MessageReceiver.ReceiveAsync(Int32 maxMessageCount, TimeSpan operationTimeout)
   at Microsoft.Azure.ServiceBus.Core.MessageReceiver.ReceiveAsync(TimeSpan operationTimeout)
   at Microsoft.Azure.ServiceBus.Core.MessageReceiver.ReceiveAsync(TimeSpan operationTimeout)
   at Microsoft.Azure.ServiceBus.Core.MessageReceiver.ReceiveAsync(TimeSpan operationTimeout)
   at Microsoft.Azure.ServiceBus.Core.MessageReceiver.ReceiveAsync(TimeSpan operationTimeout)
   at Rebus.AzureServiceBus.AzureServiceBusTransport.ReceiveInternal()
   at Rebus.AzureServiceBus.AzureServiceBusTransport.ReceiveInternal()
   at Rebus.AzureServiceBus.AzureServiceBusTransport.Receive(ITransactionContext context, CancellationToken cancellationToken)
   at Rebus.AzureServiceBus.AzureServiceBusTransport.Receive(ITransactionContext context, CancellationToken cancellationToken)
   at Rebus.Workers.ThreadPoolBased.ThreadPoolWorker.ReceiveTransportMessage(CancellationToken token, ITransactionContext context)
   at Rebus.Workers.ThreadPoolBased.ThreadPoolWorker.ReceiveTransportMessage(CancellationToken token, ITransactionContext context)
   at Rebus.Workers.ThreadPoolBased.ThreadPoolWorker.ReceiveTransportMessage(CancellationToken token, ITransactionContext context)

**Comment by mookid8000** [comment]
Hmm weird! It _could_ be a sign that the bus instance was disposed too early somehow, causing the inner message receiver to have been disposed too.

Which version of Rebus.ServiceProvider are you using?

Have you made any calls to `IBus.Dispose` anywhere in your code, or made any special registrations in the service provider involving `IBus`?

**Comment by Morshed0308** [comment]
I am using 6.4.1.
No I did not made any IBus.IDispose call in anywhere.
My rebus package now looks like this
```
<PackageReference Include="Rebus" Version="6.6.1" />
<PackageReference Include="Rebus.AzureServiceBus" Version="8.1.5" />
<PackageReference Include="Rebus.Serilog" Version="6.0.0" />
<PackageReference Include="Rebus.ServiceProvider" Version="6.4.1" />
```

**Comment by mookid8000** [comment]
While it should work, Rebus.ServiceProvider 6.4.1 is more than a year old, and lots of stuff has happened since.

Especially in version 8 of Rebus.ServiceProvider, lots of stuff has changed, because it will have much tighter integration with Microsoft's hosting APIs.

I know the 8 series is only out in prerelease versions now, but could you maybe try updating to 8.0.0-b05?
