### ISSUE TITLE
Could not find the key 'rbs2-content-type'

### ISSUE THREAD

**Issue by lukebooroo** [rebus-org/Rebus#1043]
I've had this error occurring, and it's becoming quite the mystery. Locally and on my staging server, everything is functioning correctly, once deployed to production it just stops working. I'm hoping you might be able to give me a little insight into how this could happen.

Rebus 6.6.5
Rebus.RabbitMQ 7.3.4

I'm using Rebus with RabbitMQ transport, communicating between two apps. I not sure it's relevant, but I've included the serializer configurations:

**App1: Dotnet Core 6.0**
```
      x.UseSystemJson(new JsonSerializerOptions
      {
          PropertyNamingPolicy = JsonNamingPolicy.CamelCase
      });
```

**App2: Dotnet Framework 4.8**
```
      x.UseNewtonsoftJson(new JsonSerializerSettings
      {
          ContractResolver = new DefaultContractResolver
          {
              NamingStrategy = new CamelCaseNamingStrategy
              {
                  OverrideSpecifiedNames = false
              }
          }
      });
```

On the 4.8 app, this is the error on the production server:

{"Timestamp":"2022-06-16T08:55:45.8289590+01:00","Level":"Warning","MessageTemplate":"Unhandled exception {errorNumber} while handling message with ID {messageId}","Exception":"System.Collections.Generic.KeyNotFoundException: Could not find the key 'rbs2-content-type' - have the following keys only: 'rbs2-msg-id'\r\n   at Rebus.Extensions.DictionaryExtensions.GetValue(Dictionary`2 dictionary, String key)\r\n   at Rebus.Serialization.Json.JsonSerializer.<Deserialize>d__10.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Rebus.Compression.UnzippingSerializerDecorator.<Deserialize>d__4.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Rebus.Pipeline.Receive.DeserializeIncomingMessageStep.<Process>d__2.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Rebus.DataBus.ClaimCheck.HydrateIncomingMessageStep.<Process>d__2.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Rebus.Pipeline.Receive.HandleDeferredMessagesStep.<Process>d__12.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Rebus.Retry.FailFast.FailFastStep.<Process>d__5.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Rebus.Retry.Simple.SimpleRetryStrategyStep.<DispatchWithTrackerIdentifier>d__10.MoveNext()","Properties":{"errorNumber":1,"messageId":"knuth-13208492012447682471","SourceContext":"Rebus.Retry.ErrorTracking.InMemErrorTracker"}}

Thank you in advance! :)

**Comment by mookid8000** [comment]
My initial thought was that your queue had messages in it that weren't sent by Rebus, but the presence of the header `rbs2-msg-id` kinda hints at the message stemming from Rebus.

Could you try and look at the message in the error queue? It must have been dead-lettered by now...

**Comment by lukebooroo** [comment]
Apologies. My last question was more than confusing. I think some of my issues may have been caused by having RabbitMQ.Client package still referenced in my project file. Cannot recreate the errors currently, but still having some issues with message delivery. 

I'm out of office now until Monday. Thank you for your help so far in this.

**Comment by lukebooroo** [comment]
I've spent a bit more time trying to figure this out, with little luck. It seems it's messages being sent from the CoreApp which are causing the error on the Framework app. Like I said previously only on the one server.

Getting dead letters is also proving problematic, only one 'warning' is created in the log on most occasions with the same stack trace as the dead letter below.

I've got a pretty basic configuration, which I share between the two projects in a netstandard2.0 project, the configurer is passed into this before Start is called.

```
    public static RebusConfigurer Configure(
        RebusConfigurer configurer, 
        string clientName, 
        string exchangeName)
    {
        configurer.Transport(x =>
            x.UseRabbitMq("amqp://localhost:5672", clientName)
                .ExchangeNames(exchangeName + "Direct", exchangeName + "Topics"));
        
        configurer.Logging(x => x.Serilog());

        configurer.Options(x =>
        {
            x.SetMaxParallelism(1);
            // Set this lower in an attempt to get more dead letters
            x.SimpleRetryStrategy(maxDeliveryAttempts: 2);
        });

        return configurer;
    }
```

Other than this there is the different serializer configurations which I posted above. Also the .net Framework project uses Rebus.Ninject@4.1.0

In the error logs I noted that there were different formats of the messageId when looking in the logs:
- knuth-14550753339167781612
- c948792784f71eaff0023a049d74d71c

This is one dead letter which did eventually appear:

```
Exchange	ksExchangeDirect
Routing Key	error
Redelivered	●
Properties	
message_id:	5deb7d26ea86e02ce6283a04993446d8
delivery_mode:	2
headers:	
rbs2-error-details:	System.AggregateException: 2 unhandled exceptions ---> System.Collections.Generic.KeyNotFoundException: Could not find the key 'rbs2-content-type' - have the following keys only: 'rbs2-msg-id'
at Rebus.Extensions.DictionaryExtensions.GetValue(Dictionary`2 dictionary, String key)
at Rebus.Serialization.Json.JsonSerializer.<Deserialize>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Rebus.Compression.UnzippingSerializerDecorator.<Deserialize>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Rebus.Pipeline.Receive.DeserializeIncomingMessageStep.<Process>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Rebus.DataBus.ClaimCheck.HydrateIncomingMessageStep.<Process>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Rebus.Pipeline.Receive.HandleDeferredMessagesStep.<Process>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Rebus.Retry.FailFast.FailFastStep.<Process>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Rebus.Retry.Simple.SimpleRetryStrategyStep.<DispatchWithTrackerIdentifier>d__10.MoveNext()
--- End of inner exception stack trace ---
---> (Inner Exception #0) System.Collections.Generic.KeyNotFoundException: Could not find the key 'rbs2-content-type' - have the following keys only: 'rbs2-msg-id'
at Rebus.Extensions.DictionaryExtensions.GetValue(Dictionary`2 dictionary, String key)
at Rebus.Serialization.Json.JsonSerializer.<Deserialize>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Rebus.Compression.UnzippingSerializerDecorator.<Deserialize>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Rebus.Pipeline.Receive.DeserializeIncomingMessageStep.<Process>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Rebus.DataBus.ClaimCheck.HydrateIncomingMessageStep.<Process>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Rebus.Pipeline.Receive.HandleDeferredMessagesStep.<Process>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Rebus.Retry.FailFast.FailFastStep.<Process>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Rebus.Retry.Simple.SimpleRetryStrategyStep.<DispatchWithTrackerIdentifier>d__10.MoveNext()<---

---> (Inner Exception #1) System.Collections.Generic.KeyNotFoundException: Could not find the key 'rbs2-content-type' - have the following keys only: 'rbs2-msg-id'
at Rebus.Extensions.DictionaryExtensions.GetValue(Dictionary`2 dictionary, String key)
at Rebus.Serialization.Json.JsonSerializer.<Deserialize>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Rebus.Compression.UnzippingSerializerDecorator.<Deserialize>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Rebus.Pipeline.Receive.DeserializeIncomingMessageStep.<Process>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Rebus.DataBus.ClaimCheck.HydrateIncomingMessageStep.<Process>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Rebus.Pipeline.Receive.HandleDeferredMessagesStep.<Process>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Rebus.Retry.FailFast.FailFastStep.<Process>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Rebus.Retry.Simple.SimpleRetryStrategyStep.<DispatchWithTrackerIdentifier>d__10.MoveNext()<---
rbs2-msg-id:	5deb7d26ea86e02ce6283a04993446d8
rbs2-source-queue:	ShoutSurveyClient
Payload
324 bytes
Encoding: string
{"id":""--redacted--","tenantId":""--redacted--","userName":"--redacted--","email":"--redacted--","name":null,"surname":null,"riskScore":null,"banned":null,"closedAccount":null,"isDeleted":false,"ipAddress":null,"countryCode":null,"emailConfirmed":false}
```

**Comment by mookid8000** [comment]
There's no doubt that the message you posted there is not valid for the recipient, as it's clearly lacking the `rbs2-content-type` header.

So why doesn't it have the header?

**Comment by lukebooroo** [comment]
I don't know, is the simple answer. I've been digging through your code so see how this could happen, I can find nothing. It doesn't make any sense. Being unable to reproduce the issue locally, or even on dev/staging server makes it quite impossible to debug. I've checked that all versions and such are matching.

For publish I'm simply using:

`bus.Publish(new SomeMessage {})`

I was hoping that you'd come across a similar issue at some point, and could point me in the right direction.

**Comment by mookid8000** [comment]
Btw you wrote this:

> In the error logs I noted that there were different formats of the messageId when looking in the logs:
> knuth-14550753339167781612
> c948792784f71eaff0023a049d74d71c

I think the message ID `knuth-14550753339167781612` is an artificial message ID assigned by the RabbitMQ transport, when the message does not carry a proper Rebus message ID – it's simply a [Knuth hash](https://stackoverflow.com/a/11872511/6560) of the message body.

**Comment by mookid8000** [comment]
It must come from somewhere else... what else could be putting messages into that queue?

Maybe you want to check the binding configuration in RabbitMQ to see if the queue is bound to something it should not receive, e.g. topics with wildcards or other stuff that could result in receiveing messages not intended for that particular queue.

**Comment by lukebooroo** [comment]
There's nothing else which could be sending messages. If there were, it wouldn't explain the messages with the Rebus message IDs, and missing rbs2-content-type.

**Comment by mookid8000** [comment]
Hi @lukebooroo , have you had time to look at my attempt at reproducing your issue?
