### ISSUE TITLE
Transaction Out Box - Unable to serialize null date values

### ISSUE THREAD

**Issue by pranayacodewizard** [rebus-org/Rebus#1058]
Hi Team , 
We are using Transaction out box pattern in one of our implementation. There is a requirement to send null date values to messaging queue in few cases. In that case our message processing is failed due to null date value. Below is the error. 

Please suggest for this. Please note this is a requirement to send null date values in some cases and this scenario is working if we are not using Transaction Out Box Pattern

Caused by: java.lang.NullPointerException: temporal
	at java.base/java.util.Objects.requireNonNull(Objects.java:246)
	at java.base/java.time.format.DateTimeFormatter.formatTo(DateTimeFormatter.java:1838)
	at java.base/java.time.format.DateTimeFormatter.format(DateTimeFormatter.java:1817)
	at com.gruelbox.transactionoutbox.DefaultInvocationSerializer$InstantTypeAdapter.write(DefaultInvocationSerializer.java:357)
	at com.gruelbox.transactionoutbox.DefaultInvocationSerializer$InstantTypeAdapter.write(DefaultInvocationSerializer.java:353)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:69)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.write(ReflectiveTypeAdapterFactory.java:127)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.write(ReflectiveTypeAdapterFactory.java:245)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:69)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.write(ReflectiveTypeAdapterFactory.java:127)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.write(ReflectiveTypeAdapterFactory.java:245)
	at com.google.gson.Gson.toJson(Gson.java:735)
	at com.google.gson.Gson.toJsonTree(Gson.java:628)
	at com.google.gson.Gson.toJsonTree(Gson.java:607)
	at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.serialize(TreeTypeAdapter.java:155)
	at com.gruelbox.transactionoutbox.DefaultInvocationSerializer$InvocationJsonSerializer.serialize(DefaultInvocationSerializer.java:246)
	at com.gruelbox.transactionoutbox.DefaultInvocationSerializer$InvocationJsonSerializer.serialize(DefaultInvocationSerializer.java:121)
	at com.google.gson.internal.bind.TreeTypeAdapter.write(TreeTypeAdapter.java:81)
	at com.google.gson.Gson.toJson(Gson.java:735)
	at com.google.gson.Gson.toJson(Gson.java:714)
	at com.google.gson.Gson.toJson(Gson.java:689)
	at com.gruelbox.transactionoutbox.DefaultInvocationSerializer.serializeInvocation(DefaultInvocationSerializer.java:110)

**Comment by mookid8000** [comment]
Hi @pranayacodewizard , I don't recognize anything Rebus-related in the stacktrace you have posted, so I assume it is an error that you have posted it here.
