### ISSUE TITLE
Cannot add OnCommitted action on a completed transaction context

### ISSUE THREAD

**Issue by Amanda-SVT** [rebus-org/Rebus#1070]
Hello, I am seeing an issue that I cannot find much information on and I’m not sure where things are going wrong.

I am using the timer library Quartz to schedule tasks. The basic flow of events are as follows:
- Pass a job to the Quartz scheduler to invoke when it reaches the point in time to trigger
    - The job is just a class that has an `Execute` function that is triggered when the timer occurs. 
- The job class that eventually gets an IBus instance which it then makes an awaited `bus.Send(<request>)` call
- At this point it throws the exception captured below.

I do see a comment in the code using Rebus that a similar error has occurred before and the original developer attempted to handle it by disposing the bus object and then recreating an instance before calling `Send()` once more. Frustratingly, I am not able to reliably reproduce but I can say with some degree of confidence the exception seems to only occur during times of high load where we would be invoking the `Send()` frequently, something like trying to push through ~1000 messages at about the same time.

Exception:
```
2022-12-19T22:36:40.722395184Z       Job DEFAULT.RunQuartzWorkflowInstanceJob threw an unhandled Exception: 
2022-12-19T22:36:40.722400151Z       Rebus.Exceptions.RebusApplicationException: Could not 'GetOrAdd' item with key 'outgoing-messages' as type System.Collections.Concurrent.ConcurrentQueue`1[Rebus.Transport.AbstractRebusTransport+OutgoingMessage]
2022-12-19T22:36:40.722404609Z        ---> System.InvalidOperationException: Cannot add OnCommitted action on a completed transaction context.
2022-12-19T22:36:40.722408966Z          at Rebus.Transport.TransactionContext.ThrowCompletedException(String actionName)
2022-12-19T22:36:40.722412877Z          at Rebus.Transport.TransactionContext.OnCommitted(Func`2 commitAction)
2022-12-19T22:36:40.722416860Z          at Rebus.Transport.AbstractRebusTransport.<>c__DisplayClass2_0.<Send>b__0()
2022-12-19T22:36:40.722421350Z          at Rebus.Transport.TransactionContextExtensions.<>c__DisplayClass2_0`1.<GetOrAdd>b__0(String id)
2022-12-19T22:36:40.722425615Z          at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
2022-12-19T22:36:40.722429674Z          at Rebus.Transport.TransactionContextExtensions.GetOrAdd[TItem](ITransactionContext context, String key, Func`1 newItemFactory)
2022-12-19T22:36:40.722433721Z          --- End of inner exception stack trace ---
2022-12-19T22:36:40.722437572Z          at Rebus.Transport.TransactionContextExtensions.GetOrAdd[TItem](ITransactionContext context, String key, Func`1 newItemFactory)
2022-12-19T22:36:40.722441700Z          at Rebus.Transport.AbstractRebusTransport.Send(String destinationAddress, TransportMessage message, ITransactionContext context)
2022-12-19T22:36:40.722445793Z          at Rebus.Pipeline.Send.SendOutgoingMessageStep.<>c__DisplayClass4_0.<<Send>b__0>d.MoveNext()
2022-12-19T22:36:40.722450172Z       --- End of stack trace from previous location ---
2022-12-19T22:36:40.722458315Z          at Rebus.Pipeline.Send.SendOutgoingMessageStep.Send(List`1 destinationAddressesList, TransportMessage transportMessage, ITransactionContext currentTransactionContext)
2022-12-19T22:36:40.722462536Z          at Rebus.Pipeline.Send.SendOutgoingMessageStep.Process(OutgoingStepContext context, Func`1 next)
2022-12-19T22:36:40.722466525Z          at Rebus.Pipeline.Send.ValidateOutgoingMessageStep.Process(OutgoingStepContext context, Func`1 next)
2022-12-19T22:36:40.722471701Z          at Rebus.Pipeline.Send.SerializeOutgoingMessageStep.Process(OutgoingStepContext context, Func`1 next)
2022-12-19T22:36:40.722475721Z          at Rebus.Pipeline.Send.AutoHeadersOutgoingStep.Process(OutgoingStepContext context, Func`1 next)
2022-12-19T22:36:40.722479625Z          at Rebus.Pipeline.Send.FlowCorrelationIdStep.Process(OutgoingStepContext context, Func`1 next)
2022-12-19T22:36:40.722500789Z          at Rebus.Pipeline.Send.AssignDefaultHeadersStep.Process(OutgoingStepContext context, Func`1 next)
2022-12-19T22:36:40.722504960Z          at Rebus.Bus.RebusBus.SendUsingTransactionContext(IEnumerable`1 destinationAddresses, Message logicalMessage, ITransactionContext transactionContext)
2022-12-19T22:36:40.722509050Z          at Rebus.Bus.RebusBus.InnerSend(IEnumerable`1 destinationAddresses, Message logicalMessage)
2022-12-19T22:36:40.722512958Z          at Rebus.Bus.RebusBus.Send(Object commandMessage, IDictionary`2 optionalHeaders)
2022-12-19T22:36:40.722516864Z          at Elsa.Services.Messaging.CommandSender.SendAsync(Object message, String queueName, IDictionary`2 headers, CancellationToken cancellationToken)
2022-12-19T22:36:40.722520898Z          at Elsa.Services.Dispatch.QueuingWorkflowDispatcher.DispatchAsync(ExecuteWorkflowInstanceRequest request, CancellationToken cancellationToken)
2022-12-19T22:36:40.722524897Z          at Elsa.Activities.Temporal.Quartz.Jobs.RunQuartzWorkflowInstanceJob.Execute(IJobExecutionContext context)
2022-12-19T22:36:40.722528913Z          at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)
```

Code snippets:
```
        public async Task SendAsync(object message, string? queueName = default, IDictionary<string, string>? headers = default, CancellationToken cancellationToken = default)
        {
            var bus = await GetBusAsync(message, queueName, cancellationToken);
            await _semaphore.WaitAsync(cancellationToken);
            
            // Attempt to prevent: Could not 'GetOrAdd' item with key 'new-azure-service-bus-transport' error.
            try
            {
                await bus.Send(message, headers);
            }
            catch (RebusApplicationException e)
            {
                await _serviceBusFactory.DisposeServiceBusAsync(bus, cancellationToken);
                bus = await GetBusAsync(message, queueName, cancellationToken);
                await bus.Send(message, headers);
            }
            finally
            {
                _semaphore.Release();
            }
        }
```

The function called in the `catch` block:
```
        public async Task DisposeServiceBusAsync(IBus bus, CancellationToken cancellationToken)
        {
            await _semaphore.WaitAsync(cancellationToken);

            try
            {
                bus.Dispose();
                var entry = _serviceBuses.FirstOrDefault(x => x.Value == bus);
                
                if(_serviceBuses.ContainsKey(entry.Key))
                    _serviceBuses.Remove(entry.Key);

                var busEntry = _busEntries.FirstOrDefault(x => x.Bus == bus);

                if (busEntry != null)
                    _busEntries.Remove(busEntry);
            }
            finally
            {
                _semaphore.Release();
            }
        }
```

The original files are here:
- https://github.com/elsa-workflows/elsa-core/blob/2.8.x/src/activities/Elsa.Activities.Temporal.Quartz/Jobs/RunQuartzWorkflowInstanceJob.cs
- https://github.com/elsa-workflows/elsa-core/blob/2.8.x/src/core/Elsa.Core/Services/Messaging/CommandSender.cs
- https://github.com/elsa-workflows/elsa-core/blob/2.8.x/src/core/Elsa.Core/Services/Messaging/ServiceBusFactory.cs

I understand what the exception is saying, I just don't understand how the application gets into a state where it's trying to use a completed transaction context. I am pretty inexperienced with Rebus so I would be grateful for any guidance/insight you can provide.

Thank you!

**Comment by mookid8000** [comment]
I think this is some kind of concurrency/race condition thing. The error message comes from Rebus' transaction context, which is an "ambient context" (i.e. instance held by `AsyncLocal<T>`) that spans the entire "message transaction".

A "message transaction" in this context can be

```csharp
using (var scope = new RebusTransactionScope())
{
    // the "message transaction" lasts until this scope is completed

    // bus operations are enlisted in the message transaction
    await bus.Send(whatever);

    // bus operations are enlisted in the message transaction
    await bus.Publish(whatnot);

    // and get completed here
    await scope.CompleteAsync();
}
```

or it can be whatever bus actions you perform inside a Rebus handler, because it has its own transaction context.

A message transaction can also be implicit and much shorter, because Rebus will use the exact same underlying mechanism underneath the covers when you

```csharp
await bus.Send(whatever);
```

Since me and many other people have sent/published billions of messages without getting this error, I suspect that there is something else at play here.

Looking over your source code I notice that you are using IL weaving to mess with your `await <some-task>` calls (via https://github.com/elsa-workflows/elsa-core/blob/2.8.x/src/core/Elsa.Core/FodyWeavers.xml) – do you know what actually happens when you're using that?

I.e. does it affect libraries that you're using? (e.g. Rebus?) Can it somehow affect Rebus' underlying `AsyncLocal<ITransactionContext>`?

I would suggest that you start out by simplifying your code by removing the defensive bus disposal/re-initialization bits, because that should not be necessary, and it could be another source of potential concurrency issues.

And then I suggest you disable that `.ConfigureAwait(false)` be blindly weaved into all `await`s, because I suspect that that's the source of this issue.
