### ISSUE TITLE
Unable to subscribe to messages

### ISSUE THREAD

**Issue by ShashidharB1996** [rebus-org/Rebus#1075]
Hi

I want to migrate message queue from sql server to SQS.

`
_activator = new BuiltinHandlerActivator();
_activator.Register(() => new Example.ExampleHandler(_activator.Bus));
Configure.With(_activator)
.Transport(x => x.UseAmazonSQS(SqsAcessKey, SqsSecretKey, RegionEndpoint, queueName))
.Routing(r => r.TypeBased().MapAssemblyOf(queueName))
.Subscriptions(t => t.StoreInSqlServer(ConnectionString, "Subscriptions", isCentralized: true))
.Options(b =>
{
b.SimpleRetryStrategy(
errorQueueAddress: $"{queueName}_Errors",
maxDeliveryAttempts: 1,
secondLevelRetriesEnabled: true);
b.SetNumberOfWorkers(2);
b.SetMaxParallelism(2);
})
.Start();

Bus.Subscribe().Wait();

`

This piece of code isn't working, It throws an exception at the line Bus.Subscribe().Wait(); "unable to access queue" and I dont want to use a centralized Subscription storage which should be sql server. So, I changed the transport to

`
_activator = new BuiltinHandlerActivator();
_activator.Register(() => new Example.ExampleHandler(_activator.Bus));
Configure.With(_activator)
.Transport(t => t.UseAmazonSnsAndSqs(
amazonCredentialsFactory: awsCredentials,
amazonSqsConfig: SQSConfig,
amazonSimpleNotificationServiceConfig: SNSConfig,
workerQueueAddress: queueName))
.Routing(r => r.TypeBased().Map(queueName))
.Options(b =>
{
b.SimpleRetryStrategy(
errorQueueAddress: $"{queueName}_Errors",
maxDeliveryAttempts: 1,
secondLevelRetriesEnabled: true);
b.SetNumberOfWorkers(2);
b.SetMaxParallelism(2);
})
.Start();

Bus.Subscribe().Wait();

`
This also throws an exception at the line Bus.Subscribe().Wait(); "unable to access queue".

And I'm publishing messages like this.

`
public IBus GetMessageBusForPublish(string connectionString)
{
if (_messageBus == null)
{
using (var activator = new BuiltinHandlerActivator())
{

                Configure.With(activator)
                    .Transport(x => x.UseAmazonSQSAsOneWayClient(accessKey, secretKey, RegionEndpoint))
                    .Start();

                _messageBus = activator.Bus;
            }
        }
        return _messageBus;
    }
`

I am not getting what I'm doing wrong. Please do help.

**Comment by mookid8000** [comment]
Could you post the full exception details? (i.e. including stacktrace and everything) – that will make it much easier for me to figure what is happening 🙂

**Comment by ShashidharB1996** [comment]
Exception: One or more errors occurred. (Access to the resource <url to SQS> is denied.)
Inner Exception: Exception of type 'Amazon.Runtime.Internal.HttpErrorResponseException' was thrown.

Stack trace: 
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Application(ListenerConfig config) in C:\Application\Listener.cs:line 135

Inner Exception stack trace:

   at Amazon.Runtime.Internal.HttpErrorResponseExceptionHandler.HandleExceptionStream(IRequestContext requestContext, IWebResponseData httpErrorResponse, HttpErrorResponseException exception, Stream responseStream)
   at Amazon.Runtime.Internal.HttpErrorResponseExceptionHandler.<HandleExceptionAsync>d__2.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Amazon.Runtime.Internal.ExceptionHandler`1.<HandleAsync>d__6.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at Amazon.Runtime.Internal.ErrorHandler.<ProcessExceptionAsync>d__8.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Amazon.Runtime.Internal.ErrorHandler.<InvokeAsync>d__5`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Amazon.Runtime.Internal.CallbackHandler.<InvokeAsync>d__9`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Amazon.Runtime.Internal.Signer.<InvokeAsync>d__1`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Amazon.Runtime.Internal.EndpointDiscoveryHandler.<InvokeAsync>d__2`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Amazon.Runtime.Internal.EndpointDiscoveryHandler.<InvokeAsync>d__2`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Amazon.Runtime.Internal.CredentialsRetriever.<InvokeAsync>d__7`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at Amazon.Runtime.Internal.RetryHandler.<InvokeAsync>d__10`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Amazon.Runtime.Internal.RetryHandler.<InvokeAsync>d__10`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Amazon.Runtime.Internal.CallbackHandler.<InvokeAsync>d__9`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Amazon.Runtime.Internal.CallbackHandler.<InvokeAsync>d__9`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Amazon.Runtime.Internal.ErrorCallbackHandler.<InvokeAsync>d__5`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Amazon.Runtime.Internal.MetricsHandler.<InvokeAsync>d__1`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Amazon.SQS.AmazonSQSClient.<Amazon-Runtime-SharedInterfaces-ICoreAmazonSQS-GetAttributesAsync>d__1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Rebus.AwsSnsAndSqs.RebusAmazon.Extensions.AmazonInternalSettingsExtensions.<CheckSqsPolicy>d__7.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Rebus.AwsSnsAndSqs.RebusAmazon.AmazonSqsTransport.<RegisterSubscriber>d__19.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Rebus.Bus.RebusBus.<InnerSubscribe>d__35.MoveNext()

**Comment by ShashidharB1996** [comment]
I'm trying to use SQS and SNS for publish messages, store them and subscribe to them. Hope this helps in understanding what I'm trying to achieve

**Comment by mookid8000** [comment]
The exception message
```
Exception: One or more errors occurred. (Access to the resource is denied.)
```
indicates that it's probably a problem with the keys you're using to get access to SQS.

Could you verify that the access key, secret key, and region endpoint are correct and give sufficient rights to manage queues as well as send and receive messages?

**Comment by ShashidharB1996** [comment]
What I found from Infra team was that - 
"The SQS queue has an SNS subscription attached to it, which is correctly subscribed and confirmed so any message delivered to the sqs will be sent to the sns subscription, so you would access the messages via the sns subscription but it sounds like you are trying to get messages from the sqs not the sns?"

**Comment by ShashidharB1996** [comment]
Actions on the SQS 

   "Action": [
                "sqs:ChangeMessageVisibility",
                "sqs:CreateQueue",
                "sqs:DeleteMessage",
                "sqs:DeleteQueue",
                "sqs:GetQueueUrl",
                "sqs:ReceiveMessage",
                "sqs:SetQueueAttributes"
            ]

**Comment by mookid8000** [comment]
> "The SQS queue has an SNS subscription attached to it, which is correctly subscribed and confirmed so any message delivered to the sqs will be sent to the sns subscription, so you would access the messages via the sns subscription but it sounds like you are trying to get messages from the sqs not the sns?"

I don't know anything about this particular way of configuring SQS. But I think Rebus.AmazonSQS will use SQS and not SNS, so they are absolutely right: You ARE trying to access SQS directly.

What is the purpose of having SNS in the mix here?

**Comment by ShashidharB1996** [comment]
I don't want to have Subscription storage in SQS, if I use SQS transport from Rebus.AmazonSQS package it's asking me to have a subscription storage which should be a centralized one like Sql server db, But I want to move away from db for that reason I am trying to use SNS with SQS somehow so that I won't be bound to use any db related storage for my messages.

Hope you get what I mean.

**Comment by mookid8000** [comment]
Ah ok I think I understand. But to my knowledge, you NEED to use SQL Server if you want to do pub/sub with Rebus' SQS transport, because the queueing system does not have native support for topic-based routing.

**Comment by ShashidharB1996** [comment]
I want to completely detach from databases, I don't want to use any database. Having said that I want pub/sub, what is the way to do it using SQS/SNS or both? Please any suggestions on this

**Comment by mookid8000** [comment]
> I want to completely detach from databases, I don't want to use any database.

Fair enough 🙂 

> Having said that I want pub/sub, what is the way to do it using SQS/SNS or both? Please any suggestions on this

At the moment, you'll need to either

(1) use a transport with native support for pub/sub messaging, e.g. like Azure Service Bus or RabbitMQ

or

(2) let Rebus polyfill the ability to multicast by using some kind of subscription storage.

If it bothers you that both publishers and subscribers have to be able to access the same database, you can also use Rebus + a subscription storage in DECENTRALIZED MODE (i.e. with `isCentralized: false`), which means that only publishers need to access the subscription storage. Subscribers will then need to map their events to the publisher's input queue instead*, so they can subscribe by sending a `SubscribeRequest` to the publisher (which is what happens under the covers when you `await subscriber.Subscribe<SomeEvent>();`.

---
(*) E.g. like this:
```csharp
services.AddRebus(
    configure => configure
        .Transport(t => t.(...))
        .Routing(t => t.TypeBased().Map<SomeEvent>("some-publisher"))
);
```
which will map the `SomeEvent` event to the queue named "some-publisher", causing the subscriber to direct its subscribe/unsubscribe requests there when it calls `await bus.Subscribe<SomeEvent>()`/`await bus.Unsubscribe<SomeEvent>()`

I hope that makes sense 🙂

**Comment by ShashidharB1996** [comment]
We are trying to implement the second option, still we are not sure how to establish this.

**Comment by mookid8000** [comment]
Have you checked the wiki?

E.g. https://github.com/rebus-org/Rebus/wiki/Pub-sub-messaging has some info about centralized vs. decentralized subscription storage.

**Comment by mookid8000** [comment]
Hi @ShashidharB1996 , did you get your things up and running? 🙂 

I'll just close this issue for now. Feel free to get back in here if you still have questions!

**Comment by krunal-jethva-tark** [comment]
Hey @mookid8000 I'm having a same problem but could not find any useful pointer how to achieve this, so I don't have database dependency.  and also there is no sample implementation for `SQS` in [RebusSamples](https://github.com/rebus-org/RebusSamples). It would be great to have SQS sample with this scenario.

My reason for using SQS is it is cheap and reliable on top that I can access it from anywhere in my application, compare to solution like RabbitMQ, Database, Msmq where I need to handle so many things on my own.

**Comment by mookid8000** [comment]
@krunal-jethva-tark What problem are you having?

**Comment by krunal-jethva-tark** [comment]
Hi @mookid8000

I'm currently working on an application that involves a branching concept, where changes made by a parent to data or permissions should be synchronized to child databases. To achieve this, I'm planning to use AWS SQS and SNS. The idea is that when a parent makes a change, the modification will be added to a queue, and the child will fetch it from there to perform the necessary insert, update, or delete operations in its own database.

I'm leaning towards using SQS and SNS over self-managed RabbitMQ due to their cost-effectiveness and reliability. Setting up and maintaining a RabbitMQ server on EC2 or another service seems like it would be more resource-intensive and potentially less reliable in the long run. Would you agree with this assessment, or do you think there are other factors I should consider in making this decision?

I've been trying to find documentation or demos that can help me with implementing SQS, but I haven't had much luck so far. Could you point me towards any resources that might be helpful in this regard?

Additionally, in first comment, author mentioned a method called `UseAmazonSnsAndSqs` that links SQS and SNS. However, I haven't been able to find this method in the documentation or the code. Am I looking in the wrong place

> (2) let Rebus polyfill the ability to multicast by using some kind of subscription storage.
> 
> If it bothers you that both publishers and subscribers have to be able to access the same database, you can also use Rebus + a subscription storage in DECENTRALIZED MODE (i.e. with `isCentralized: false`), which means that only publishers need to access the subscription storage. Subscribers will then need to map their events to the publisher's input queue instead*, so they can subscribe by sending a `SubscribeRequest` to the publisher (which is what happens under the covers when you `await subscriber.Subscribe<SomeEvent>();`.

Lastly, I'm a bit confused about the statement you made regarding subscribers needing to map their events to the publisher's input queue. How exactly would a subscriber do this, and how would they be notified when the publisher publishes something in the SQS queue?

**Comment by mookid8000** [comment]
> I'm leaning towards using SQS and SNS over self-managed RabbitMQ due to their cost-effectiveness and reliability. Setting up and maintaining a RabbitMQ server on EC2 or another service seems like it would be more resource-intensive and potentially less reliable in the long run. Would you agree with this assessment, or do you think there are other factors I should consider in making this decision?

I definitely agree with you that managing your own RabbitMQ would be more tedious than using PaaS services like e.g. Amazon SQS. Moreover, it would require a pretty serious effort to provide the same level of availability.

> I've been trying to find documentation or demos that can help me with implementing SQS, but I haven't had much luck so far. Could you point me towards any resources that might be helpful in this regard?

Check out [the Usage section of README.md in the Rebus.AmazonSQS repo](https://github.com/rebus-org/Rebus.AmazonSQS/blob/master/README.md#usage).

> Additionally, in first comment, author mentioned a method called UseAmazonSnsAndSqs that links SQS and SNS. However, I haven't been able to find this method in the documentation or the code. Am I looking in the wrong place

I am not familiar with UseAmazonSnsAndSqs, sorry.

> Lastly, I'm a bit confused about the statement you made regarding subscribers needing to map their events to the publisher's input queue. How exactly would a subscriber do this, and how would they be notified when the publisher publishes something in the SQS queue?

Please read [the Routing page](https://github.com/rebus-org/Rebus/wiki/Routing) and [the subscription storage page](https://github.com/rebus-org/Rebus/wiki/ISubscriptionStorage) on the documentation wiki. 🙂 They explain how routing works in Rebus and how you can have pub/sub messaging with any transport, even though the transport itself does not natively support it (which Amazon SQS does not).
