### ISSUE TITLE
Throw exception immediately upon connection failure - FailFastChecker not working

### ISSUE THREAD

**Issue by ryanhendersonabs** [rebus-org/Rebus#1091]
I have a situation where we are trying to connect to a remote RabbitMQ instance that may be unreachable on a regular basis (intermittent connectivity at the edge). To avoid spamming our logs with warnings and constantly retrying, I would prefer that Rebus just throws an exception if the connection fails.

Initially, I thought FailFastChecker might help here, but it doesn't appear to come into play with connection errors (only message handling exceptions).

Basically, I just want an exception to be thrown that I can catch and handle rather than seeing tons of these:
![image](https://github.com/rebus-org/Rebus/assets/130497203/5b347f88-42c4-4a45-a150-5989432e6ca4)

Furthermore, it appears that if the connection fails for long enough, Rebus eventually crashes with a different top-level exception (not what I would expect). Is there a better/proper way to achieve what we're trying to achieve?
```
Rebus.Injection.ResolutionException: Could not resolve Rebus.Bus.IBus with decorator depth 0 - registrations: Rebus.Injection.Injectionist+Handler
 ---> Rebus.Exceptions.RebusApplicationException: Queue declaration for 'test-rebus-queue-remote' failed
 ---> RabbitMQ.Client.Exceptions.BrokerUnreachableException: None of the specified endpoints were reachable
 ---> RabbitMQ.Client.Exceptions.OperationInterruptedException: The AMQP operation was interrupted: AMQP close-reason, initiated by Peer, code=530, text='NOT_ALLOWED - vhost mmeiyyvfzzzzz not found', classId=10, methodId=40
   at RabbitMQ.Client.Impl.SimpleBlockingRpcContinuation.GetReply(TimeSpan timeout)
   at RabbitMQ.Client.Impl.ModelBase.ConnectionOpen(String virtualHost, String capabilities, Boolean insist)
   at RabbitMQ.Client.Framing.Impl.Connection.Open(Boolean insist)
   at RabbitMQ.Client.Framing.Impl.Connection..ctor(IConnectionFactory factory, Boolean insist, IFrameHandler frameHandler, String clientProvidedName)
   at RabbitMQ.Client.Framing.Impl.Connection..ctor(IConnectionFactory factory, Boolean insist, IFrameHandler frameHandler, ArrayPool`1 memoryPool, String clientProvidedName)
   at RabbitMQ.Client.Framing.Impl.AutorecoveringConnection.Init(IFrameHandler fh)
   at RabbitMQ.Client.Framing.Impl.AutorecoveringConnection.Init(IEndpointResolver endpoints)
   at RabbitMQ.Client.ConnectionFactory.CreateConnection(IEndpointResolver endpointResolver, String clientProvidedName)
   --- End of inner exception stack trace ---
   at RabbitMQ.Client.ConnectionFactory.CreateConnection(IEndpointResolver endpointResolver, String clientProvidedName)
   at RabbitMQ.Client.ConnectionFactory.CreateConnection(IList`1 endpoints, String clientProvidedName)
   at RabbitMQ.Client.ConnectionFactory.CreateConnection(IList`1 endpoints)
   at Rebus.Internals.ConnectionManager.GetConnection()
   at Rebus.RabbitMq.RabbitMqTransport.CreateQueue(String address)
   --- End of inner exception stack trace ---
   at Rebus.RabbitMq.RabbitMqTransport.CreateQueue(String address)
   at Rebus.RabbitMq.RabbitMqTransport.Initialize()
   at Rebus.Config.RebusConfigurer.<>c__DisplayClass13_0.<Start>b__28(IResolutionContext c)
   at Rebus.Injection.Injectionist.Resolver`1.InvokeResolver(IResolutionContext context)
   at Rebus.Injection.Injectionist.ResolutionContext.Get[TService]()
   --- End of inner exception stack trace ---
   at Rebus.Injection.Injectionist.ResolutionContext.Get[TService]()
   at Rebus.Injection.Injectionist.Get[TService]()
   at Rebus.Config.RebusConfigurer.Start()
   at [our background worker].ExecuteAsync(CancellationToken stoppingToken) in [...]:line 29
```

**Comment by mookid8000** [comment]
You are absolutely correct that the "fail fast" mechanism is only about how Rebus handles messages and whether or not to allow for retries there.

When starting up with the RabbitMQ transport, Rebus will retry for one minute when it makes its initial connection attempt to try to declare its own input queue.

There's no way at the moment to avoid this. It works like this because it has helped in many situations where the RabbitMQ server could not be reached immdiately when starting up, and then waiting up to 60 seconds for it to come online has been a nice way to handle that.

I'm afraid that that's just how it works at the moment, so I can't really say that there's a better way for you to check if your RabbitMQ is online with Rebus.
