### ISSUE TITLE
MSDTC on server 'x' is unavailable.

### ISSUE THREAD

**Issue by oguzhaneren** [rebus-org/Rebus#378]
Hi,

I want to publish events (or send commands) after my nhibernate transaction complete so I installed Rebus.TransactionScope nuget package and enlist transaction scope like this:

<pre>
 using (TransactionScope scope = new TransactionScope(TransactionScopeAsyncFlowOption.Enabled))
 {
     scope.EnlistRebus();
     var session = sessionFactory.OenSession();
     var tx = session.BeginTransaction();
     session.Save(myDomainObj);
     _bus.Publish(new NameChanged("blabla"));
     transaction.Commit();
     session.Dispose();
     scope.Complete();
 }
</pre>

Ado.net throw exception:"MSDTC on server 'x' is unavailable." however use of same database in transactionscope don't need msdtc.

My rebus configuration:

<pre>
var conn ="server=localhost;database=my-db;user=user;password=pass";
    Configure.With(new SimpleInjectorContainerAdapter(Container))
     .Logging(l => l.NLog())
     .Transport(sc =>
     {
         sc.UseSqlServer(conn, "rebus-queue", "main-queue");
     })
     .Subscriptions(ss =>
     {
         ss.StoreInSqlServer(conn, "rebus-subscriptions");
     })
     .Options(oc => {})
     .Routing(r => r.TypeBased().MapAssemblyOf<NameChanged>("main-queue"))
     .Start();
</pre>

**Comment by mookid8000** [comment]
Which line causes the exception to be thrown?

**Comment by oguzhaneren** [comment]
I forgot to add "session.Dispose();" line to example code. This line causes error, there is no error when I removed that line but there is new error when I call " _bus.Publish(new NameChanged("blabla"));"

- WHERE IS THE REBUS TRANSCATION?

**Comment by oguzhaneren** [comment]
I found problem that causes the "WHERE IS THE REBUS TRANSCATION?" 

Background worker stole transaction some way. Maybe I should manage rebus & container separately for received messages.

Issue can close.

**Comment by mookid8000** [comment]
oh
try putting an `await` in front of that `bus.Publish` - like this:

    await _bus.Publish(new NameChanged("blabla"));

There will most likely be some kind of pretty-hard-to-predict race condition if you don't await the call.

**Comment by oguzhaneren** [comment]
@mookid8000 I don't use async methods but I use like <pre>_bus.Publish(new NameChanged("blabla")).Wait()</pre>

**Comment by oguzhaneren** [comment]
I splitted container and rebus like your blog post: "http://mookid.dk/oncode/archives/4008 " but rebus thrown exception WHERE IS THE REBUS TRANSCATION?

**Comment by mookid8000** [comment]
First off: I am no expert on DTC, but as far as I know, there's no reason why the transaction should escalate to become a distributed transaction with the code you have shown. I may be wrong though.

Can I get you to paste in the full exception details?

**Comment by asgerhallas** [comment]
@oguzhaneren which version of SQL Server are you running?

**Comment by oguzhaneren** [comment]
@asgerhallas I'm using Sql Server 2014 Dev Edt.

@mookid8000 there is no exception details :)

<pre>
System.InvalidOperationException was unhandled
Message: An unhandled exception of type 'System.InvalidOperationException' occurred in Rebus.TransactionScopes.dll
Additional information: WHERE IS THE REBUS TRANSCATION?

</pre>
![screenshot_1](https://cloud.githubusercontent.com/assets/2587216/11741510/3d32d6a8-a002-11e5-9d63-ecaabb936527.png)

Here my sample code:
<pre>
// Configuration

var conn ="server=localhost;database=my-db;user=user;password=pass";

// WebClient
var webClientContainer = new Container();
// RegisterComponentsTo(webclientContainer);
var clientBus = Configure.With(new SimpleInjectorContainerAdapter(webClientContainer))
        .Logging(l => l.ColoredConsole())
        .Transport(sc =>
        {
            sc.UseSqlServerAsOneWayClient(conn, "rebus-queue");
        })
        .Subscriptions(ss =>
        {
            ss.StoreInSqlServer(conn, "rebus-subscriptions");
        })
        .Routing(r => r.TypeBased().MapAssemblyOf<NameChanged>("main-queue"))
        .Start()



// Background Worker
var backgroundWorkerContainer = new Container();
// RegisterComponentsTo(backgroundWorkerContainer);
var backgroundBus = Configure.With(new SimpleInjectorContainerAdapter(_container))
      .Logging(l => l.ColoredConsole())
      .Transport(sc =>
      {
          sc.UseSqlServer(conn, "rebus-queue", "main-queue");
      })
      .Subscriptions(ss =>
      {
          ss.StoreInSqlServer(conn, "rebus-subscriptions");
      })
      .Options(oc =>
      {
          oc.HandleMessagesInsideTransactionScope();
      })
      .Routing(r => r.TypeBased().MapAssemblyOf<NameChanged>("main-queue"))
       .Start();
background.Bus.Subscribe<NameChanged>().Wait();



// Client 
using (TransactionScope scope = new TransactionScope(TransactionScopeAsyncFlowOption.Enabled))
{
    scope.EnlistRebus();
    var transaction = _session.BeginTransaction();
    var rec = _session.Get<Record>(1);
    rec.ChangeName("blablala")
    _clientBus.Publish(new NameChanged(rec.Name)).Wait();
    transaction.Commit();
    scope.Complete();
}




// Background app
public class ActivityHandler
:IHandleMessages<NameChanged>{
  public class   ActivityHandler(ISession session){ }
  public Task Handle(NameChanged ev){
    _session.Save(Activity.FromEvent(ev));
  }
}


</pre>

**Comment by asgerhallas** [comment]
@oguzhaneren I missed the message above where you say, that the issue could be closed :)

**Comment by mookid8000** [comment]
:laughing: LOL sorry! I though it was you that made that spelling error.... "TRANSCATION"..... but I did that, and it's because Rebus' ambient transaction has somehow been removed.

I'll look into it - just a moment :)

**Comment by oguzhaneren** [comment]
@asgerhallas issue changed little bit

**Comment by mookid8000** [comment]
but @oguzhaneren  - could you "copy exception details to clipboard" and paste it in here? I would like to see a full stack trace....

**Comment by oguzhaneren** [comment]
there is no stack trace in error message

**Comment by mookid8000** [comment]
it's somewhere underneath it all :) try the "copy exception details" thing

**Comment by mookid8000** [comment]
The Visual Studio exception visualization is crap

**Comment by oguzhaneren** [comment]
Exception details same with 
<pre>
System.InvalidOperationException was unhandled
Message: An unhandled exception of type 'System.InvalidOperationException' occurred in Rebus.TransactionScopes.dll
Additional information: WHERE IS THE REBUS TRANSCATION?
</pre>

I tried to add try-catch block to wrap publish function, but debugger stops after exception so catch never be triggered

**Comment by mookid8000** [comment]
that is so weird

**Comment by mookid8000** [comment]
I think I know what's wrong.... let me just see if I can fix it

**Comment by oguzhaneren** [comment]
sometimes I received this error, maybe it will be related with wierd transaction error

<pre>
Rebus.Threading.AsyncTask WARN (Thread #15): Exception in periodic task 'ExpiredMessagesCleanup': System.Data.SqlClient.SqlException (0x80131904): The parameterized query '(@recipient nvarchar(200))
DELETE FROM [rebus-queue]
    WHER' expects the parameter '@recipient', which was not supplied.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString)
   at System.Data.SqlClient.SqlCommand.CompleteAsyncExecuteReader()
   at System.Data.SqlClient.SqlCommand.EndExecuteNonQueryInternal(IAsyncResult asyncResult)
   at System.Data.SqlClient.SqlCommand.EndExecuteNonQueryAsync(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Rebus.Transport.SqlServer.SqlServerTransport.<PerformExpiredMessagesCleanupCycle>d__27.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Rebus.Threading.AsyncTask.<>c__DisplayClass15_0.<<Start>b__0>d.MoveNext()
ClientConnectionId:acbd58fe-7b91-4f14-8fab-af720da286f3
Error Number:8178,State:1,Class:16
</pre>

**Comment by mookid8000** [comment]
I've pushed 0.99.21 to NuGet.org - could you try the `TransactionScope` thing again?

**Comment by mookid8000** [comment]
PS: The Sql Exception is another thing - I'll look into that too :)

**Comment by oguzhaneren** [comment]
I tried, exception changes:
<pre>
The operation is not valid for the state of the transaction.

StackTrace:
   at System.Transactions.TransactionState.EnlistPromotableSinglePhase(InternalTransaction tx, IPromotableSinglePhaseNotification promotableSinglePhaseNotification, Transaction atomicTransaction, Guid promoterType)
   at System.Transactions.Transaction.EnlistPromotableSinglePhase(IPromotableSinglePhaseNotification promotableSinglePhaseNotification, Guid promoterType)
   at System.Transactions.Transaction.EnlistPromotableSinglePhase(IPromotableSinglePhaseNotification promotableSinglePhaseNotification)
   at System.Data.SqlClient.SqlInternalConnection.EnlistNonNull(Transaction tx)
   at System.Data.SqlClient.SqlInternalConnection.Enlist(Transaction tx)
   at System.Data.SqlClient.SqlInternalConnectionTds.Activate(Transaction transaction)
   at System.Data.ProviderBase.DbConnectionInternal.ActivateConnection(Transaction transaction)
   at System.Data.ProviderBase.DbConnectionPool.PrepareConnection(DbConnection owningObject, DbConnectionInternal obj, Transaction transaction)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at Rebus.Persistence.SqlServer.DbConnectionProvider.<GetConnection>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Rebus.Transport.SqlServer.SqlServerTransport.<>c__DisplayClass29_0.<<GetConnection>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Rebus.Transport.SqlServer.SqlServerTransport.<Send>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Rebus.Pipeline.Send.SendOutgoingMessageStep.<Send>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Rebus.Pipeline.Send.SendOutgoingMessageStep.<Process>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Rebus.Pipeline.Send.SerializeOutgoingMessageStep.<Process>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Rebus.Pipeline.Send.AutoHeadersOutgoingStep.<Process>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Rebus.Pipeline.Send.FlowCorrelationIdStep.<Process>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Rebus.Pipeline.Send.AssignDateTimeOffsetHeader.<Process>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Rebus.Pipeline.Send.AssignReturnAddressStep.<Process>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Rebus.Pipeline.Send.AssignGuidMessageIdStep.<Process>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Rebus.Pipeline.DefaultPipelineInvoker.<Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Rebus.Bus.RebusBus.<SendUsingTransactionContext>d__37.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Rebus.Bus.RebusBus.<InnerSend>d__36.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Rebus.Bus.RebusBus.<InnerPublish>d__27.MoveNext()

</pre>

**Comment by mookid8000** [comment]
oh shit, I think I know what it is - you're using the SQL Server transport, and because ADO.NET is crazy, it automatically enlists in the ambient transaction...... which causes the transaction to escalate to DTC, which is definitely not what we want.... just a moment

**Comment by mookid8000** [comment]
I'm making a small fix now, but I want the build server to finish testing before I make a release..... I'll let you know when it's ready

**Comment by oguzhaneren** [comment]
ok, thanks :+1:

**Comment by asgerhallas** [comment]
@mookid8000 just a quick thought... to my knowlegde, that shouldn't escalate the transaction (as it is the same connection string for both the transport and nhibernate), unless it keeps multiple connections open at the same time... why would it do that in this scenario?

**Comment by oguzhaneren** [comment]
multiple connection with same connectionstring doesn't need to dtc

![ghuaz](https://cloud.githubusercontent.com/assets/2587216/11745130/7a57d0bc-a01e-11e5-9817-5601bc5b369a.png)

**Comment by asgerhallas** [comment]
@oguzhaneren exactly, unless they are open at the same time.

**Comment by oguzhaneren** [comment]
I tested it yesterday, it works, [transaction scope (nhibernate - outgoint transport) ]

When bus transport failed or transaction scope commit not called, nhibernate transaction be rollbacked.

**Comment by mookid8000** [comment]
the thing is though that Rebus by itself enables [MARS](https://msdn.microsoft.com/en-us/library/h32h3abf(v=vs.110).aspx) because the transport needs to be able to do that - that makes the connection string in effect different from the one passed in, causing escalation to DTC

**Comment by mookid8000** [comment]
can we close this one?

**Comment by oguzhaneren** [comment]
@mookid8000 yes
