### ISSUE TITLE
System.ArgumentException: An item with the same key has already been added.

### ISSUE THREAD

**Issue by takinosaji** [rebus-org/Rebus#567]
Hi Rebus team!
Recently tied to process new message type in our project and got this exception:

2016-12-10 22:26:06 INFO  Rebus.RabbitMq.ConnectionManager: Initializing RabbitMQ connection manager for transport with input queue 'MyQueue'
2016-12-10 22:26:06 INFO  Rebus.RabbitMq.ConnectionManager: Creating new RabbitMQ connection
2016-12-10 22:26:06 INFO  Rebus.Threading.TaskParallelLibrary.TplAsyncTask: Starting periodic task 'CleanupTrackedErrors' with interval 00:01:00
2016-12-10 22:26:06 INFO  Rebus.Threading.TaskParallelLibrary.TplAsyncTask: Starting periodic task 'DueMessagesSender' with interval 00:00:01
2016-12-10 22:26:06 INFO  Rebus.Bus.RebusBus: Starting bus 3
2016-12-10 22:26:06 INFO  Rebus.Bus.RebusBus: Setting number of workers to 5
2016-12-10 22:26:06 DEBUG Rebus.Bus.RebusBus: Adding worker Rebus 3 worker 1
2016-12-10 22:26:06 DEBUG Rebus.Bus.RebusBus: Adding worker Rebus 3 worker 2
2016-12-10 22:26:06 DEBUG Rebus.Workers.ThreadPoolBased.ThreadPoolWorker: Starting (threadpool-based) worker Rebus 3 worker 1
2016-12-10 22:26:06 DEBUG Rebus.Bus.RebusBus: Adding worker Rebus 3 worker 3
2016-12-10 22:26:06 DEBUG Rebus.Workers.ThreadPoolBased.ThreadPoolWorker: Starting (threadpool-based) worker Rebus 3 worker 2
2016-12-10 22:26:06 DEBUG Rebus.Bus.RebusBus: Adding worker Rebus 3 worker 4
2016-12-10 22:26:06 DEBUG Rebus.Workers.ThreadPoolBased.ThreadPoolWorker: Starting (threadpool-based) worker Rebus 3 worker 3
2016-12-10 22:26:06 DEBUG Rebus.Workers.ThreadPoolBased.ThreadPoolWorker: Starting (threadpool-based) worker Rebus 3 worker 4
2016-12-10 22:26:06 DEBUG Rebus.Bus.RebusBus: Adding worker Rebus 3 worker 5
2016-12-10 22:26:06 INFO  Rebus.RabbitMq.RabbitMqTransport: Successfully initialized consumer for MyQueue
2016-12-10 22:26:06 DEBUG Rebus.Workers.ThreadPoolBased.ThreadPoolWorker: Starting (threadpool-based) worker Rebus 3 worker 5
2016-12-10 22:26:06 INFO  Rebus.Bus.RebusBus: Started
2016-12-10 22:26:06 ERROR Rebus.Workers.ThreadPoolBased.ThreadPoolWorker: Unhandled exception while handling message MyMessageType/knuth-13156575018460464302
System.ArgumentException: An item with the same key has already been added.

Message headers:
rbs2-intent:	pub
rebus-msg-id:	b255b54f-834b-4c4d-9527-76ecc665db2a
rbs2-senttime:	2016-12-10T22:45:07.2322785+01:00
rebus-correlation-id:	b255b54f-834b-4c4d-9527-76ecc665db2a
rbs2-corr-seq:	0
rbs2-msg-type:	MyMessageType, My.Namespace
rbs2-content-type:	application/json;charset=utf-7
rebus-content-type:	text/json
rebus-encoding:	utf-7

Could you help me to understand where problem might be?

**Comment by mookid8000** [comment]
I have no idea why it causes that exception, but I can see that the message ID header of your message has the wrong key - it should be `rbs2-msg-id`

**Comment by mookid8000** [comment]
Actually the headers look like a mix of Rebus 1 and Rebus 2 headers

**Comment by takinosaji** [comment]
I have legacyCompaitibility enabled. Message is created by Rebus2

**Comment by SvenVandenbrande** [comment]
Can you maybe create a smaller application with the problem? So the same nuget packages & code... 
It will be probably easier to find the problem. :)

**Comment by takinosaji** [comment]
This is configuration of receiving bus: 
http://screencast.com/t/osUZouwPeFy3

This is configuration of sending bus:
http://screencast.com/t/N7YURqGN5

**Comment by SvenVandenbrande** [comment]
And the nuget packages for both?

**Comment by takinosaji** [comment]
Nuget packages 1st part: http://screencast.com/t/SKmmPRAY4

**Comment by takinosaji** [comment]
Question. As far as i understand EnableLegacyCompatibility makes Rebus2 send messages with Rebus1 compatible headers. But is it capable to consume messages produced by itself? I am enabling legacy compatibility for receiving bus but maybe it is useless and here is a problem?

**Comment by SvenVandenbrande** [comment]
And on the other application?

**Comment by takinosaji** [comment]
The same. I am using my library in one application. One bus is opened to send messages another to process. How i configure sending and receiving bus i've shown in prev post.

**Comment by SvenVandenbrande** [comment]
?? But you have Rebus 1 & Rebus 2 messages?

**Comment by mookid8000** [comment]
> Question. As far as i understand EnableLegacyCompatibility makes Rebus2 send messages with Rebus1 compatible headers. But is it capable to consume messages produced by itself? I am enabling legacy compatibility for receiving bus but maybe it is useless and here is a problem?

@takinosaji When you `EnableLegacyCompatibility`, you make Rebus 2 transform all headers of incoming and outgoing messages to/from Rebus 1 format. This means that you need to enable legacy compatibility across ALL endpoints for this to work.

I recommend you upgrade all of your Rebus endpoints to version 2 soon, as the legacy compatibility feature is going away in Rebus 3.

**Comment by takinosaji** [comment]
@mookid8000 thx for notification. As son as we can we will update our endpoints to Rebus2 
@SvenVandenbrande current problem occurred inside one application with message sent via Rebus2 to Rebus2. In both sending and receiving bus legacy compatibility enabled.

**Comment by mookid8000** [comment]
> current problem occurred inside one application with message sent via Rebus2 to Rebus2. In both sending and receiving bus legacy compatibility enabled

ah, I think I realize now what happened: 

* when the RabbitMQ transport receives a message with an ID, it will [automatically assign a "fake" ID](https://github.com/rebus-org/Rebus.RabbitMq/blob/master/Rebus.RabbitMq/RabbitMq/RabbitMqTransport.cs#L378-L391) based on a [Knuth hash](https://www.google.dk/search?q=knuth+hash) of the message body
* the legacy compatibility incoming message mapper will not map the message ID because one is already present
* some other code assumed it could `dictionary.Add(messageId, <something>)` and be sure that the message ID was unique

and the third step fails because you cannot assume that message IDs are unique (as in: you CAN, but the same message can be delivered more than once if something fails)

**Comment by takinosaji** [comment]
@mookid8000  Thanks for details. So do you see ways to resolve it? Problem is inside rebus code or Rabbitmq client?

**Comment by mookid8000** [comment]
> Problem is inside rebus code or Rabbitmq client?

it's hard to tell from the log you posted – can you include the stack trace?

**Comment by takinosaji** [comment]
@mookid8000 that's all i've gotten from Rebus log. Exception isn't thrown in our code.  Also upon failing of handling of the message it tries to handle it again so we have infinite loop of errors in log.

**Comment by mookid8000** [comment]
> that's all i've got from Rebus log

You should do something to adjust your logging then – it is close to useless when it doesn't include stack traces.

I went and reproduced the issue, and this is what I got:

      Rebus.Workers.ThreadPoolBased.ThreadPoolWorker ERROR (Rebus 1 worker 1): Unhandled exception while handling message String/knuth-7374892804131625181
      System.ArgumentException: An item with the same key has already been added.
         at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
         at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
         at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
         at Rebus.Legacy.MapLegacyHeadersIncomingStep.MapTrivialHeaders(Dictionary`2 headers)
         at Rebus.Legacy.MapLegacyHeadersIncomingStep.MutateLegacyTransportMessage(IncomingStepContext context, Dictionary`2 headers, TransportMessage transportMessage)
         at Rebus.Legacy.MapLegacyHeadersIncomingStep.<Process>d__1.MoveNext()
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         at Rebus.Workers.ThreadPoolBased.ThreadPoolWorker.<ProcessMessage>d__18.MoveNext()

from which it clearly shows that the exception is thrown in the `MapTrivialHeaders` method of the `MapLegacyHeadersIncomingStep` step when it tries to convert a list of headers to a dictionary.

This tells me that there must be a duplicate key among the headers of the incoming message, a hypothesis which is further supported by the fact that I just found out that the RabbitMq transport will add a surrogate `rbs2-msg-id` header if it does not find one.

Combined with the `rebus-msg-id` which is then mapped to`rbs2-msg-id` there will suddenly be two headers with that key.

This is where you will get an exception :smile:

**Comment by mookid8000** [comment]
In summary, the problem is that Rebus' RabbitMQ transport conflicts with how the [unsupported legacy mode](https://github.com/rebus-org/Rebus/issues/490#issuecomment-234521268) works.

So – how can it be fixed?

Either by

a) upgrading all endpoints to Rebus 2 – this is definitely the preferred solution, as this will bring you up on a supported version where things are guaranteed to work, or

b) implementing a decorator for `ITransport` that removes the artificially added message ID from received messages

I really recommend you go do (a).
