### ISSUE TITLE
error loading config

### ISSUE THREAD

**Issue by stevengopmo** [rebus-org/Rebus#597]
Hi

We are getting the following error when trying to load configuration from the app.config file on our server (seems to work fine locally).

`Service cannot be started. System.Configuration.ConfigurationErrorsException: An error occurred creating the configuration section handler for rebus: Could not load type 'Rebus.Configuration.RebusConfigurationSection' from assembly 'Rebus'. (C:\Files\cm\services\cs.CM.Approval\CodySoft.Approval.Rebus.Host.exe.Config line 4) ---> System.TypeLoadException: Could not load type 'Rebus.Configuration.RebusConfigurationSection' from assembly 'Rebus'.
   at System.Configuration.TypeUtil.GetTypeWithReflectionPermission(IInternalConfigHost host, String typeString, Boolean throwOnError)
   at System.Configuration.RuntimeConfigurationRecord.RuntimeConfigurationFactory.Init(RuntimeConfigurationRecord configRecord, FactoryRecord factoryRecord)
   at System.Configuration.RuntimeConfigurationRecord.RuntimeConfigurationFactory.InitWithRestrictedPermissions(RuntimeConfigurationRecord configRecord, FactoryRecord factoryRecord)
   at System.Configuration.RuntimeConfigurationRecord.CreateSectionFactory(FactoryRecord factoryRecord)
   at System.Conf...`

our config section looks like this

````  
<configSections>
    <section name="rebus" type="Rebus.Configuration.RebusConfigurationSection, Rebus" />
  </configSections>
  
  <rebus inputQueue="cs.cm.approval" errorQueue="cs.cm.approval.error" workers="1">
    <endpoints>
      <add messages="cs.Platform.InternalMessages.Commands.MessageCenter.CreateMessage, cs.Platform.InternalMessages" endpoint="cs.Platform.Acknowledge" />
      <add messages="cs.Platform.InternalMessages.Commands.MessageCenter.CreateNotification, cs.Platform.InternalMessages" endpoint="cs.Platform.Acknowledge" />
    </endpoints>
  </rebus>
````
Any ideas why this would fail to load on the server (Windows Server 2012 R2)?  It's probably something silly but I just can't spot it.

**Comment by stevengopmo** [comment]
doh!  server had a legacy version of the section.  All better now :)

**Comment by mookid8000** [comment]
👍 😁  good to hear you figured it out
