### ISSUE TITLE
Could not Load type RebusTransactionScope

### ISSUE THREAD

**Issue by robvanpamel** [rebus-org/Rebus#620]
Hi, 

I'm getting the exception as described below after updating to the latest versions of Rebus

Unhandled Exception: Rebus.Injection.ResolutionException: Could not resolve Rebus.Bus.IBus with decorator depth 0 - registrations: Rebus.Injection.Injectionist+Handler ---> System.TypeLoadException: Could not load type 'Rebus.Transport.RebusTransactionScope' from assembly 'Rebus, Version=4.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at Rebus.AmazonSQS.AmazonSQSTransport.GetInputQueueUrl()
   at Rebus.AmazonSQS.AmazonSQSTransport.Initialize()
   at Rebus.Config.RebusConfigurer.<>c__DisplayClass12_1.<Start>b__23(IResolutionContext c)
   at Rebus.Injection.Injectionist.ResolutionContext.Get[TService]()
   --- End of inner exception stack trace ---
   at Rebus.Injection.Injectionist.ResolutionContext.Get[TService]()
   at Rebus.Injection.Injectionist.Get[TService]()
   at Rebus.Config.RebusConfigurer.Start()
   at Sag.CityCenter.Api.Messaging.BusConfigurer.Initialize(String environment) in /home/rob/git/svc-cityform/src/Sag.CityCenter.Api/Messaging/BusConfigurer.cs:line 51
   at Sag.CityCenter.Api.Extensions.ContainerExtensions.ConfigureRebus(IContainer container, String environment) in /home/rob/git/svc-cityform/src/Sag.CityCenter.Api/Extensions/ContainerExtensions.cs:line 12
   at Sag.CityCenter.Api.Startup.ConfigureServices(IServiceCollection services) in /home/rob/git/svc-cityform/src/Sag.CityCenter.Api/Startup.cs:line 83

Am i doing something wrong, or do I have to register this manual in the container ? 

Kind Regards
  Rob

**Comment by mookid8000** [comment]
Did you update everything Rebus to version 4.0.0-* ?

**Comment by robvanpamel** [comment]
You are right, there was a Library which was still using an older version. I upgraded that library and it was resolved! thanks!
