### ISSUE TITLE
Saga exception running in Rebus in an Azure App

### ISSUE THREAD

**Issue by seankearon** [rebus-org/Rebus#624]
I've got a Rebus installation which uses SQL Server Saga storage running on a VM in Azure and I'm moving it to run in an Azure Web App.  When I run Rebus in the Azure App I get the exception below from the Saga.  It all works fine in the VM and, as far as I can see, I'm doing exactly the same in both.  

Any ideas where I can look for this?

`5 unhandled exceptions: 6/29/2017 6:53:25 AM +00:00: Rebus.Exceptions.ConcurrencyException: Could not update index for saga with ID 47b12ba4-4b1d-4426-bdc5-f22e857f8710 because of a PK violation - there must already exist a saga instance that uses one of the following correlation properties: FormUid='90572710-a036-4073-ad62-60f7de8ad121'
   at Rebus.SqlServer.Sagas.SqlServerSagaStorage.<CreateIndex>d__23.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Rebus.SqlServer.Sagas.SqlServerSagaStorage.<Insert>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Rebus.Sagas.LoadSagaDataStep.<SaveSagaData>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Rebus.Sagas.LoadSagaDataStep.<SaveSagaData>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Rebus.Sagas.LoadSagaDataStep.<Process>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Rebus.Pipeline.Receive.ActivateHandlersStep.<Process>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Rebus.Pipeline.Receive.DeserializeIncomingMessageStep.<Process>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Rebus.Auditing.Messages.IncomingAuditingStep.<Process>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Rebus.Retry.Simple.SimpleRetryStrategyStep.<DispatchWithTrackerIdentifier>d__7.MoveNext()
6/29/2017 6:53:25 AM +00:00: Rebus.Exceptions.ConcurrencyException: Update of saga with ID 2ef5cf82-45d0-4a51-9417-62806cd0f136 did not succeed because someone else beat us to it
   at Rebus.SqlServer.Sagas.SqlServerSagaStorage.<Update>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Rebus.Sagas.LoadSagaDataStep.<SaveSagaData>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Rebus.Sagas.LoadSagaDataStep.<SaveSagaData>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Rebus.Sagas.LoadSagaDataStep.<Process>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Rebus.Pipeline.Receive.ActivateHandlersStep.<Process>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Rebus.Pipeline.Receive.DeserializeIncomingMessageStep.<Process>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Rebus.Auditing.Messages.IncomingAuditingStep.<Process>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Rebus.Retry.Simple.SimpleRetryStrategyStep.<DispatchWithTrackerIdentifier>d__7.MoveNext()
6/29/2017 6:53:25 AM +00:00: Rebus.Exceptions.ConcurrencyException: Update of saga with ID 2ef5cf82-45d0-4a51-9417-62806cd0f136 did not succeed because someone else beat us to it
   at Rebus.SqlServer.Sagas.SqlServerSagaStorage.<Update>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Rebus.Sagas.LoadSagaDataStep.<SaveSagaData>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Rebus.Sagas.LoadSagaDataStep.<SaveSagaData>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Rebus.Sagas.LoadSagaDataStep.<Process>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Rebus.Pipeline.Receive.ActivateHandlersStep.<Process>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Rebus.Pipeline.Receive.DeserializeIncomingMessageStep.<Process>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Rebus.Auditing.Messages.IncomingAuditingStep.<Process>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Rebus.Retry.Simple.SimpleRetryStrategyStep.<DispatchWithTrackerIdentifier>d__7.MoveNext()
6/29/2017 6:53:25 AM +00:00: Rebus.Exceptions.ConcurrencyException: Update of saga with ID 2ef5cf82-45d0-4a51-9417-62806cd0f136 did not succeed because someone else beat us to it
   at Rebus.SqlServer.Sagas.SqlServerSagaStorage.<Update>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Rebus.Sagas.LoadSagaDataStep.<SaveSagaData>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Rebus.Sagas.LoadSagaDataStep.<SaveSagaData>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Rebus.Sagas.LoadSagaDataStep.<Process>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Rebus.Pipeline.Receive.ActivateHandlersStep.<Process>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Rebus.Pipeline.Receive.DeserializeIncomingMessageStep.<Process>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Rebus.Auditing.Messages.IncomingAuditingStep.<Process>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Rebus.Retry.Simple.SimpleRetryStrategyStep.<DispatchWithTrackerIdentifier>d__7.MoveNext()
6/29/2017 6:53:26 AM +00:00: Rebus.Exceptions.ConcurrencyException: Update of saga with ID 2ef5cf82-45d0-4a51-9417-62806cd0f136 did not succeed because someone else beat us to it
   at Rebus.SqlServer.Sagas.SqlServerSagaStorage.<Update>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Rebus.Sagas.LoadSagaDataStep.<SaveSagaData>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Rebus.Sagas.LoadSagaDataStep.<SaveSagaData>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Rebus.Sagas.LoadSagaDataStep.<Process>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Rebus.Pipeline.Receive.ActivateHandlersStep.<Process>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Rebus.Pipeline.Receive.DeserializeIncomingMessageStep.<Process>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Rebus.Auditing.Messages.IncomingAuditingStep.<Process>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Rebus.Retry.Simple.SimpleRetryStrategyStep.<DispatchWithTrackerIdentifier>d__7.MoveNext()`

**Comment by mookid8000** [comment]
There should be no difference at all between hosting Rebus in a web app and hosting it on a VM.

The only way I can see that this error could arise, is if you let an incoming message – which is NOT correlated to the saga's `FormUid` property with the value `90572710-a036-4073-ad62-60f7de8ad121` – initiate a new saga and set its `FormUid` property to `90572710-a036-4073-ad62-60f7de8ad121`.

Could you check out and see if that is the case?

**Comment by mookid8000** [comment]
oops, didn't mean to close it before we have solved your issue 😄

**Comment by seankearon** [comment]
Hehe - no worries! :)

Okay, thanks.  As far as I can see it all looks as it should.  Here's how the saga is set up and correlated:

    public class FormProcessingSaga : Saga<FormProcessingSagaData>,
        IAmInitiatedBy<ProcessFormCommand>,
        IHandleMessages<FormDataMigrated>,
        // snip
    {
        protected override void CorrelateMessages(ICorrelationConfig<FormProcessingSagaData> c)
        {
            c.Correlate<ProcessFormCommand>(m => m.FormUid, s => s.FormUid);
            c.Correlate<FormDataMigrated>(m => m.FormUid, s => s.FormUid);
            // snip
        }
        public async Task Handle(ProcessFormCommand m)
        {
            if (!IsNew) return;
            Data.FormUid = m.FormUid;
            // snip

I've checked it with the `PayoutSaga` in [RebusSamples](https://github.com/rebus-org/RebusSamples/blob/master/Sagas/SagaDemo/Handlers/PayoutSaga.cs) and it seems to match the way that's working.  Mind you, I've been staring at this for so long now that perhaps I'm just not seeing something obvious!

What seems to be happening is that the first `ProcessFormCommand` message is picked up, the saga is created and then that first message is sent straight to the error queue.  From inspection of the audit queue, the saga doesn't issue any other messages.  After that the DB looks like this:

![image](https://user-images.githubusercontent.com/455924/27723322-6ecdf46a-5d64-11e7-990b-9bccedc54412.png)

Let me try isolating this into a test case and see what comes from that.  Back soon...

**Comment by seankearon** [comment]
The test case works perfectly, so it looks like it's a problem somewhere in my other Azure bus code.  So I'm closing this now...thanks for your help though, much appreciated! :)

**Comment by mookid8000** [comment]
that's weird! let me know if I can be of any help 😄

**Comment by seankearon** [comment]
In case this helps anyone in the same situation, the problem turned out to be caused by me registering Rebus handlers, and hence sagas, more than once.  

I am using Autofac and scanning the assemblies for Rebus handlers to register into the Autofac container.  It was as simple as me doing this in two separate Autofac modules, causing the double registration, which gave two sagas trying to start from the same message and correlation ID.

Thanks to @mookid8000 for helping to sort this out!
