### ISSUE TITLE
[QUESTION] ServiceBus exception

### ISSUE THREAD

**Issue by vdecristofaro** [rebus-org/Rebus#670]
I have a component which uses rebus to offload real time reporting tasks to a consumer.
Actually this component is used with no problems for thousands of times a day.

Last day, December 29th, I had a problem for about one hour that is making me crazy to understand the causes. I know that the problem is not about Rebus, I am just posting it in here to ask for any hint on the understanding.

The problem arised intermittently on the `await bus.Send( event );` and did never happened before.

The error message was the following

> System.TimeoutException: The request operation did not complete within the allotted timeout of 00:00:31.3270136. The time allotted to this operation may have been a portion of a longer timeout. For more information on exception types and proper exception handling, please refer to http://go.microsoft.com/fwlink/?LinkId=761101 TrackingId:de74f3bf-f8b9-45b3-953e-1eda016a39d8

Obviously, if I visit the link suggested I am not able to find any message like mine, even if there are some very criptic informations about TimeoutException generally. Also there are no info on the Azure status page of any system downgrade during the period that this error occurred.

I am also attaching the complete stack trace for further reference.
```
    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    at Microsoft.ServiceBus.Common.AsyncResult.End[TAsyncResult](IAsyncResult result)
    at Microsoft.ServiceBus.Messaging.Sbmp.DuplexRequestBindingElement.DuplexRequestSessionChannel.EndRequest(IAsyncResult result)
    at Microsoft.ServiceBus.Messaging.Channels.ReconnectBindingElement.ReconnectChannelFactory`1.RequestSessionChannel.RequestAsyncResult.<>c.<GetAsyncSteps>b__9_3(RequestAsyncResult thisPtr, IAsyncResult r)
    at Microsoft.ServiceBus.Messaging.IteratorAsyncResult`1.StepCallback(IAsyncResult result)
    --- End of stack trace from previous location where exception was thrown ---
    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    at Microsoft.ServiceBus.Common.AsyncResult.End[TAsyncResult](IAsyncResult result)
    at Microsoft.ServiceBus.Messaging.Channels.ReconnectBindingElement.ReconnectChannelFactory`1.RequestSessionChannel.EndRequest(IAsyncResult result)
    at Microsoft.ServiceBus.Messaging.Sbmp.RedirectBindingElement.RedirectContainerChannelFactory`1.RedirectContainerSessionChannel.RequestAsyncResult.<>c__DisplayClass8_1.<GetAsyncSteps>b__4(RequestAsyncResult thisPtr, IAsyncResult r)
    at Microsoft.ServiceBus.Messaging.IteratorAsyncResult`1.StepCallback(IAsyncResult result)
    --- End of stack trace from previous location where exception was thrown ---
    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    at Microsoft.ServiceBus.Common.AsyncResult.End[TAsyncResult](IAsyncResult result)
    at Microsoft.ServiceBus.Messaging.Sbmp.RedirectBindingElement.RedirectContainerChannelFactory`1.RedirectContainerSessionChannel.EndRequest(IAsyncResult result)
    at Microsoft.ServiceBus.Messaging.Channels.ReconnectBindingElement.ReconnectChannelFactory`1.RequestSessionChannel.RequestAsyncResult.<>c.<GetAsyncSteps>b__9_3(RequestAsyncResult thisPtr, IAsyncResult r)
    at Microsoft.ServiceBus.Messaging.IteratorAsyncResult`1.StepCallback(IAsyncResult result)
    --- End of stack trace from previous location where exception was thrown ---
    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    at Microsoft.ServiceBus.Common.AsyncResult.End[TAsyncResult](IAsyncResult result)
    at Microsoft.ServiceBus.Messaging.Channels.ReconnectBindingElement.ReconnectChannelFactory`1.RequestSessionChannel.EndRequest(IAsyncResult result)
    at Microsoft.ServiceBus.Messaging.Sbmp.SbmpTransactionalAsyncResult`1.<>c.<GetAsyncSteps>b__18_3(TIteratorAsyncResult thisPtr, IAsyncResult a)
    at Microsoft.ServiceBus.Messaging.IteratorAsyncResult`1.StepCallback(IAsyncResult result)
    --- End of stack trace from previous location where exception was thrown ---
    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    at Microsoft.ServiceBus.Common.AsyncResult.End[TAsyncResult](IAsyncResult result)
    at Microsoft.ServiceBus.Messaging.Sbmp.SbmpMessageSender.EndSendCommand(IAsyncResult result)
    at Microsoft.ServiceBus.Messaging.BatchManager`1.PerformFlushAsyncResult.OnSingleOperationCompleted(IAsyncResult result)
    --- End of stack trace from previous location where exception was thrown ---
    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    at Microsoft.ServiceBus.Common.AsyncResult.End[TAsyncResult](IAsyncResult result)
    at Microsoft.ServiceBus.Messaging.BatchManager`1.EndFlush(IAsyncResult result)
    --- End of stack trace from previous location where exception was thrown ---
    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    at Microsoft.ServiceBus.Common.AsyncResult.End[TAsyncResult](IAsyncResult result)
    at Microsoft.ServiceBus.Messaging.BatchManagerAsyncResult`1.OnBatchedCallback(IAsyncResult result)
    at Microsoft.ServiceBus.Common.AsyncResult.AsyncCompletionWrapperCallback(IAsyncResult result)
    --- End of stack trace from previous location where exception was thrown ---
    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    at Microsoft.ServiceBus.Common.AsyncResult.End[TAsyncResult](IAsyncResult result)
    at Microsoft.ServiceBus.Messaging.Sbmp.SbmpMessageSender.OnEndSend(IAsyncResult result)
    at Microsoft.ServiceBus.Messaging.IteratorAsyncResult`1.StepCallback(IAsyncResult result)
    --- End of stack trace from previous location where exception was thrown ---
    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    at Microsoft.ServiceBus.Common.AsyncResult.End[TAsyncResult](IAsyncResult result)
    at Microsoft.ServiceBus.Messaging.MessageSender.<>c.<SendAsync>b__44_1(IAsyncResult a)
    at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
    --- End of stack trace from previous location where exception was thrown ---
    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    at Rebus.AzureServiceBus.AzureServiceBusTransport.<Send>d__36.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    at Rebus.AzureServiceBus.AzureServiceBusTransport.<>c__DisplayClass35_2.<<GetOutgoingMessages>b__3>d.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    at Rebus.AzureServiceBus.Retrier.<Execute>d__4.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    at Rebus.AzureServiceBus.AzureServiceBusTransport.<>c__DisplayClass35_3.<<GetOutgoingMessages>b__2>d.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    at Rebus.AzureServiceBus.AzureServiceBusTransport.<>c__DisplayClass35_1.<<GetOutgoingMessages>b__1>d.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    at Rebus.Transport.TransactionContext.<Invoke>d__24.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    at Rebus.Transport.TransactionContext.<RaiseCommitted>d__21.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    at Rebus.Transport.TransactionContext.<Complete>d__19.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    at Rebus.Bus.RebusBus.<InnerSend>d__41.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    at Rebus.Bus.RebusBus.<Send>d__21.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    at MyCompany.MyProject.Producer.MyEventTrigger.<RaiseEvent>d__3.MoveNext() 

```

Thanks for reading.

**Comment by mookid8000** [comment]
This is quite hard to diagnose, because the connection issue could be caused by a lot of things.

Is your component hosted in Azure as well?

**Comment by vdecristofaro** [comment]
Hello @mookid8000, thanks for your answer. 
Yes, both the producer and the consumer components are hosted on Azure. The first is a web api application while the second is embedded into an mvc app.
The main visibile problem my users experienced was of course related to performance downgrade because of the timeout occurred. To avoid this I can of course wrap the Send into something smarter that handle a shorter timeout but I am also interested in understanding the real reasons to better address any solution.

**Comment by mookid8000** [comment]
> both the producer and the consumer components are hosted on Azure

Then I would say that it rules out my hypothesis of you having some kind of local network problem 😁 

Unfortunately, Azure Service Bus is not always as available as one would wish for it to be. My colleague once experienced receive timeouts, and after a thorough investigation of his own code, he got in touch with Microsoft. 

The bad receive performance turned out to be caused by a "noisy neighbor", in this case another customer who had enqueued billions of messages – and since the underlying storage was shared between that customer's and our ASB instance, our performance was severely affected by it.

The fix was to simply create a new ASB namespace and move our stuff to that. I suggest you do the same if you experience this issue again.

**Comment by vdecristofaro** [comment]
Do you think it would be feasible implementing and exposing a retry strategy directly in the Rebus.AzureStorage package?

https://docs.microsoft.com/en-us/azure/architecture/best-practices/retry-service-specific#service-bus-retry-guidelines

**Comment by mookid8000** [comment]
Yeah, it would probably be a good thing to do, actually

**Comment by jr01** [comment]
We experience this `TimeoutException` with `bus.Send()` to Azure ServiceBus with code that runs outside of a Rebus messagehandler from time to time. In our case the operationtimeout is 1 minute. We are hosted in Azure and yesterday there were about 15 error entries in the logs for a duration of roughly 20 minutes. This time-frame overlapped with Microsoft applying a hotfix to several Azure service bus servers. Of course this timeout can also happen in other situations.

I noticed that in [AzureServiceBusTransport.cs](https://github.com/rebus-org/Rebus.AzureServiceBus/blob/master/Rebus.AzureServiceBus/AzureServiceBus/AzureServiceBusTransport.cs) `GetRetrier()` method the `TimeoutException` isn't handled/retried.

Based on the information here [https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-messaging-exceptions#timeoutexception](https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-messaging-exceptions#timeoutexception)   I guess it's debatable if Rebus should retry the `TimeoutException` by default.

One argument for retrying, but perhaps not a very good one, is that when Send() is done inside of a Rebus message handler, the Rebus message handling pipeline will retry the send anyway. 

A plug-able retry strategy would be nice as a solution. Another option could be a simple setting in the AzureServiceBusTransportSettings. For now (we are on Rebus v3) I'll try adding a custom outgoing step in the Rebus pipeline that retries this `TimeoutException`. 

@mookid8000  Perhaps re-open this issue?
