### ISSUE TITLE
error when use filesystem as the transport

### ISSUE THREAD

**Issue by endink** [rebus-org/Rebus#674]
I used the filesystem as the transport, an error occurred, but the error message does not have any valuable information in callstack, please use “throw;” instead of "throw exception" to handle the exception.

my subscriptions

```
_configure = Configure.With(_activator)
                .Logging(c => c.Use(new WrappedLoggerFactory(loggerFactory)))
                .Transport(t => t.UseFileSystem(dir, queueOptions.Value.QueueName.IfNullOrWhiteSpace("messages")))
                .Subscriptions(s => s.StoreInSqlite(dir));

            _configure.Start();
            foreach (var msgType in _messageTypes)
            {
                _activator.Bus.Subscribe(msgType).GetAwaiter().GetResult();
            }
```

my pub
```
_activator = new BuiltinHandlerActivator();
            Configure.With(_activator)
               .Logging(c => c.Use(new WrappedLoggerFactory(loggerFactory)))
               .Transport(t => t.UseFileSystemAsOneWayClient(dir))
               .Subscriptions(s=>s.StoreInSqlite(dir))
               .Routing(r =>
               {
                   var mappings = r.TypeBased();
                   foreach (var t in messageTypes)
                   {
                       mappings.Map(t, "messages");
                   }
               })
               .Start();

         ......
        _activator.Bus.Send(parameter);
```
error:
```
warn: InMemErrorTracker[0]
            Unhandled exception 1 while handling message with ID "5e97af57-d2d8-4827-8190-b225f16b5b2c"
            Application:front ver:1.0.0
            Time: 2018-01-19 17:15:07
            Host: 169.254.25.127
            Environment: development
            Rebus.Exceptions.RebusApplicationException:
            Rebus.Exceptions.RebusApplicationException: Message with ID 5e97af57-d2d8-4827-8190-b225f16b5b2c and type Labijie.Site.Test, Labijie.Site could not be dispatched to any handlers
               at Rebus.Pipeline.Receive.DispatchIncomingMessageStep.<Process>d__3.MoveNext()
            --- End of stack trace from previous location where exception was thrown ---
               at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
               at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
               at Rebus.Sagas.LoadSagaDataStep.<Process>d__6.MoveNext()
            --- End of stack trace from previous location where exception was thrown ---
               at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
               at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
               at Rebus.Pipeline.Receive.ActivateHandlersStep.<Process>d__3.MoveNext()
            --- End of stack trace from previous location where exception was thrown ---
               at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
               at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
               at Rebus.Pipeline.Receive.HandleRoutingSlipsStep.<Process>d__3.MoveNext()
            --- End of stack trace from previous location where exception was thrown ---
               at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
               at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
               at Rebus.Pipeline.Receive.DeserializeIncomingMessageStep.<Process>d__2.MoveNext()
            --- End of stack trace from previous location where exception was thrown ---
               at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
               at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
               at Rebus.Pipeline.Receive.HandleDeferredMessagesStep.<Process>d__12.MoveNext()
            --- End of stack trace from previous location where exception was thrown ---
               at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
               at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
               at Rebus.Retry.FailFast.FailFastStep.<Process>d__3.MoveNext()
            --- End of stack trace from previous location where exception was thrown ---
               at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
               at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
               at Rebus.Retry.Simple.SimpleRetryStrategyStep.<DispatchWithTrackerIdentifier>d__8.MoveNext()

```

**Comment by mookid8000** [comment]
Hi @endink , you should take a look at the first couple of lines from the exception text you posted:
```
warn: InMemErrorTracker[0]
            Unhandled exception 1 while handling message with ID "5e97af57-d2d8-4827-8190-b225f16b5b2c"
            Application:front ver:1.0.0
            Time: 2018-01-19 17:15:07
            Host: 169.254.25.127
            Environment: development
            Rebus.Exceptions.RebusApplicationException:
            Rebus.Exceptions.RebusApplicationException: Message with ID 5e97af57-d2d8-4827-8190-b225f16b5b2c and type Labijie.Site.Test, Labijie.Site could not be dispatched to any handlers
(......)
```
I know it contains many lines, but the first lines have a description of the error:

    Message with ID 5e97af57-d2d8-4827-8190-b225f16b5b2c and type
    Labijie.Site.Test, Labijie.Site could not be dispatched to any handlers

If you add a handler for messages of type `Test` like this:

    _activator.Handle<Test>(async message => {
        // handle the message in here
    });

then I bet that will fix the error.

**Comment by endink** [comment]
What is the difference between register and Handle, I thought that using the Register method to register a factory can work, many methods are confusing, such as Handle, Register, Subscribe, whether consider merging in one method to process the subscription

**Comment by mookid8000** [comment]
Well, Rebus has quite a few methods.

I can recommend going to [the wiki](https://github.com/rebus-org/Rebus/wiki) to read about the different concepts and see how they're exposed in Rebus' API, and then you might want to look at [the samples](https://github.com/rebus-org/RebusSamples) too, as they have quite a few running examples – for example, pub/sub messaging is demonstrated in [this sample](https://github.com/rebus-org/RebusSamples/tree/master/PubSub).
