### ISSUE TITLE
Generic RebusContainer - Problems with mapping the routings

### ISSUE THREAD

**Issue by arnarleifs** [rebus-org/Rebus#709]
I have multiple services which all rely on the Bus for different scenarios. My thoughts were to refactor the code and create a class called RebusContainer.cs which creates a Bus context for each service. This is an old project which was setup using Rebus version 0.84 but I am updating as well to the newest version, so there is a lot to think about. 

I am currently receiving an error which looks like this:

```
Attempted to register primary -> Rebus.Routing.IRouter, but a primary registration already exists: primary -> Rebus.Routing.IRouter
   at Rebus.Injection.Injectionist.Register[TService](Func`2 resolverMethod, Boolean isDecorator, String description)
   at Rebus.Injection.Injectionist.Register[TService](Func`2 resolverMethod, String description)
   at Rebus.Config.StandardConfigurer`1.Register(Func`2 factoryMethod, String description)
   at Rebus.Routing.TypeBased.TypeBasedRouterConfigurationExtensions.TypeBased(StandardConfigurer`1 configurer)
   at MyNameSpace.Common.RebusContainer.<>c__DisplayClass0_1.<SetupRebus>b__4(SubscriptionMessage sub) in C:\Projects\MyProject\MyNameSpace\RebusContainer.cs:line 34
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at MyNameSpace.Common.RebusContainer.<>c__DisplayClass0_0.<SetupRebus>b__3(StandardConfigurer`1 r) in C:\Projects\MyProject\MyNameSpace\RebusContainer.cs:line 34
   at Rebus.Config.RebusConfigurer.Routing(Action`1 configurer)
   at MyNameSpace.Common.RebusContainer.<>c__DisplayClass0_0.<SetupRebus>b__0(RebusConfigurer configurer, IComponentContext context) in C:\Projects\MyProject\MyNameSpace\RebusContainer.cs:line 30
   at Rebus.Config.ContainerBuilderExtensions.<>c__DisplayClass1_0.<RegisterRebus>b__0(RebusConfigurer configurer, IComponentContext context)
   at Rebus.Autofac.AutofacHandlerActivator.<>c__DisplayClass3_0.<.ctor>b__1(IComponentContext context)
   at Autofac.RegistrationExtensions.<>c__DisplayClass5_0`1.<Register>b__0(IComponentContext c, IEnumerable`1 p)
   at Autofac.Builder.RegistrationBuilder.<>c__DisplayClass0_0`1.<ForDelegate>b__0(IComponentContext c, IEnumerable`1 p)
   at Autofac.Core.Activators.Delegate.DelegateActivator.ActivateInstance(IComponentContext context, IEnumerable`1 parameters)
   at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters)
```

I am not what I am doing wrong, although I know it is linked to the Route mappings somehow. Below is both the service calling the RebusContainer as well as the RebusContainer too.

_Service.cs_
![image](https://user-images.githubusercontent.com/9974384/41030171-3ad3d9e8-696d-11e8-9ee1-5c472e87319d.png)

_RebusContainer.cs_
![image](https://user-images.githubusercontent.com/9974384/41030233-5e1466ac-696d-11e8-80e5-069f336bcd17.png)

**Comment by mookid8000** [comment]
The problem is this line:
```csharp
.Routing(r => subscriptions.ForEach(sub => r.TypeBased().Map(...))
```
because it calls `TypeBased()` multiple times and thus tries to register an `IRouter` multiple times.

If you change it to:
```csharp
.Routing(r => {
    var routing = r.TypeBased();

    subscriptions.ForEach(sub => routing.Map(...));
})
```
then it should work 😄
