### ISSUE TITLE
Subscribing to many event types can be slow

### ISSUE THREAD

**Issue by MortenChristiansen** [rebus-org/Rebus#754]
We use Azure Message Queues and find that the process of subscribing to all our event types is very slow. Currently it takes over 3 seconds to register 9 events in parallel on my machine. This does not scale to a system that will have hundreds of event types.

A quick look into the code, it seems that Rebus makes a remote lookup per event which makes sense. I was hoping that this process can be optimized for bulk subscriptions somehow so we do not have to delay the startup of our system while waiting a long time. This issue could really slow down our development flow as we have to wait for this each time we start a web service or run and integration test.

**Comment by mookid8000** [comment]
When you say "Azure Message Queues" do you then mean Azure Service Bus?

**Comment by MortenChristiansen** [comment]
Yes, that is correct.

**Comment by mookid8000** [comment]
I've made an improvement now that avoids a full roundtrip per subscription registration, when the subscription is found to be existing already.

It's out in Rebus.AzureServiceBus 6.0.4 in a few minutes when the build server finishes munching through the tests.

I'm curious to hear how it works out for you, especially when running in Azure.

**Comment by MortenChristiansen** [comment]
It was a bit faster, though not as much as I had hoped. It went from around 3.5s to 2.8s to subscribe to the 9 event types. I'll add further measurements when we get a bit mere events in our system as well as how it behaves in Azure. I'm still worried that the duration will become a major headache during development, but time will tell.

However, I did get a non-reproducible null reference exception during the subscription once. I would guess that it is a threading issue since we subscribe to the events in parallel. Is the operation supposed to be thread safe? If not we have a serious problem, since the 2.8s go up to 12.5s when processed serially.

Here is the stack trace:
```
   at System.Net.Http.HttpConnection.WriteStringAsync(String s)
   at System.Net.Http.HttpConnection.WriteHeadersAsync(HttpHeaders headers, String cookiesFromContainer)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithNtConnectionAuthAsync(HttpConnection connection, HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Microsoft.Azure.ServiceBus.Management.ManagementClient.SendHttpRequest(HttpRequestMessage request, CancellationToken cancellationToken) in C:\source\azure-service-bus-dotnet\src\Microsoft.Azure.ServiceBus\Management\ManagementClient.cs:line 1104
   at Microsoft.Azure.ServiceBus.Management.ManagementClient.PutEntity(String path, String requestBody, Boolean isUpdate, String forwardTo, String fwdDeadLetterTo, CancellationToken cancellationToken) in C:\source\azure-service-bus-dotnet\src\Microsoft.Azure.ServiceBus\Management\ManagementClient.cs:line 1062
   at Microsoft.Azure.ServiceBus.Management.ManagementClient.UpdateSubscriptionAsync(SubscriptionDescription subscriptionDescription, CancellationToken cancellationToken) in C:\source\azure-service-bus-dotnet\src\Microsoft.Azure.ServiceBus\Management\ManagementClient.cs:line 739
   at Rebus.AzureServiceBus.AzureServiceBusTransport.RegisterSubscriber(String topic, String subscriberAddress)
   at Rebus.Bus.RebusBus.InnerSubscribe(String topic) in C:\projects-rebus\Rebus\Rebus\Bus\RebusBus.cs:line 279
```

**Comment by MortenChristiansen** [comment]
Right now my registration code looks like this:
```csharp
public void SubscribeToHandledEvents(IBus bus, List<Type> eventTypes)
{
    Task.WaitAll(eventTypes.Select(e => SubscribeWithRetry(bus, e)).ToArray());
}

private async Task SubscribeWithRetry(IBus bus, Type eventType)
{
    var triesLeft = 3;
    while (triesLeft-- > 0)
    {
        try
        {
            await bus.Subscribe(eventType);
            return;
        }
        catch (NullReferenceException)
        {
        }
    }
}
```
