### ISSUE TITLE
Could not resolve Rebus.Bus.IBus with decorator depth 0

### ISSUE THREAD

**Issue by vegar** [rebus-org/Rebus#758]
I have a **.net core 2.1** console app, hosted in service fabric cluster.

Relevant nuget packages:

-  Rebus, v5.0.1
-  Rebus.AzureServicebus, v6.0.4
-  Rebus.Serilog, v5.0.0
-  Rebus.ServiceProvider, v4.0.1
-  Microsoft.Azure.Servicebus, v3.1.0

When deployed to the local cluster, everything works ok, but when deployed to azure, I get the following exception, and the service fails to start:

```
Replica had multiple failures during open on _nt1vm_2. API call: IStatelessServiceInstance.Open(); Error = Rebus.Injection.ResolutionException (-2146233088)
Could not resolve Rebus.Bus.IBus with decorator depth 0 - registrations: Rebus.Injection.Injectionist+Handler
   at Rebus.Injection.Injectionist.ResolutionContext.Get[TService]()
   at Rebus.Injection.Injectionist.Get[TService]()
   at Rebus.Config.RebusConfigurer.Start()
   at Shareregister.ProvisioningService.Rebus.ServiceBusCommunicationListener.OpenAsync(CancellationToken cancellationToken)
   at Microsoft.ServiceFabric.Services.Runtime.StatelessServiceInstanceAdapter.OpenCommunicationListenersAsync(CancellationToken cancellationToken)
   at Microsoft.ServiceFabric.Services.Runtime.StatelessServiceInstanceAdapter.System.Fabric.IStatelessServiceInstance.OpenAsync(IStatelessServicePartition partition, CancellationToken cancellationToken)
```

I'm setting up rebus within a custom `ICommunicationListener` like this:

```
public async Task<string> OpenAsync(CancellationToken cancellationToken)
        {
            _activator = new NetCoreServiceProviderContainerAdapter(_provider);

            var bus = Configure
                .With(_activator)
                .Logging(x => x.Serilog())
                .Transport(t => t.UseAzureServiceBus(connectionStringNameOrConnectionString: _rebusOptions.ConnectionString, inputQueueAddress: _rebusOptions.InputQueue))
                .Options(o =>
                {
                    o.SimpleRetryStrategy(_rebusOptions.ErrorQueue);
                })
                .Start();

            await bus.Subscribe<CompanyAddedEventMessage>();

            return _rebusOptions.ConnectionString;
        }
```

Does anyone have any clue where to start hunting?
Is there a way of getting a more detailed exception (serilog is not getting anything useful..) ?

**Comment by mookid8000** [comment]
Could you add a `try`...`catch` around the body inside the `OpenAsync` method shown above, and then log the caught exception?

It's as if lots of important stuff is missing in the stack trace above.

**Comment by vegar** [comment]
Good advice! 

``` 
2018-11-15 14:58:31.406 +00:00 [ERR] Exception in OpenAsync: Could not resolve Rebus.Bus.IBus with decorator depth 0 - registrations: Rebus.Injection.Injectionist+Handler - Could not create Azure Service Bus queue 'sharregister' {  }
Rebus.Injection.ResolutionException: Could not resolve Rebus.Bus.IBus with decorator depth 0 - registrations: Rebus.Injection.Injectionist+Handler ---> System.ArgumentException: Could not create Azure Service Bus queue 'sharregister' ---> Microsoft.Azure.ServiceBus.UnauthorizedException: Authorization failed for specified action: Manage. TrackingId:29c644db-c0ce-48fc-8314-30adbf35e8ba_G14, SystemTracker:vismaadvisorytools-common-int.servicebus.windows.net:sharregister, Timestamp:11/15/2018 2:58:31 PM
   at Microsoft.Azure.ServiceBus.Management.ManagementClient.SendHttpRequest(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Azure.ServiceBus.Management.ManagementClient.PutEntity(String path, String requestBody, Boolean isUpdate, String forwardTo, String fwdDeadLetterTo, CancellationToken cancellationToken)
   at Microsoft.Azure.ServiceBus.Management.ManagementClient.CreateQueueAsync(QueueDescription queueDescription, CancellationToken cancellationToken)
   at Rebus.AzureServiceBus.AzureServiceBusTransport.<>c__DisplayClass24_0.<<CreateQueue>b__1>d.MoveNext()
   --- End of inner exception stack trace ---
   at Rebus.AzureServiceBus.AzureServiceBusTransport.<>c__DisplayClass24_0.<<CreateQueue>b__1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Rebus.Internals.AsyncHelpers.CustomSynchronizationContext.<Run>b__7_0(Object _)
   at Rebus.Internals.AsyncHelpers.CustomSynchronizationContext.Run()
   at Rebus.Internals.AsyncHelpers.RunSync(Func`1 task)
   at Rebus.AzureServiceBus.AzureServiceBusTransport.Initialize()
   at Rebus.Config.RebusConfigurer.<>c__DisplayClass12_0.<Start>b__26(IResolutionContext c)
   at Rebus.Injection.Injectionist.ResolutionContext.Get[TService]()
   --- End of inner exception stack trace ---
   at Rebus.Injection.Injectionist.ResolutionContext.Get[TService]()
   at Rebus.Injection.Injectionist.Get[TService]()
   at Rebus.Config.RebusConfigurer.Start()
   at Shareregister.ProvisioningService.Rebus.ServiceBusCommunicationListener.OpenAsync(CancellationToken cancellationToken)
```

**Comment by mookid8000** [comment]
> Is there a way of getting a more detailed exception (serilog is not getting anything useful..) ?

Seems more like it's the way Serilog was being used in this case, because when you pass an exception to Serilog, it will log everything about it.

Is it some kind of "official" Serilog integration for Service Fabric, or how did you hook it up with Serilog?

**Comment by vegar** [comment]
I'm not sure, actually. A lot of unexplored terrain here...

BUT what I do know, is that a connection string which is 'send-only' will cause trouble when trying to create subscriptions. That I've learned today.

**Comment by vegar** [comment]
Looking over my code, I can't really say I've done anything to connect service fabrics and serilog - except for adding it to the service container.... But I've hooked it up with rebus, though.

**Comment by mookid8000** [comment]
Oh, but then the problem is that Rebus throws an exception when starting up.

Rebus should not log that – that's the responsibility of the caller, in this case Service Fabric.

It looks like Service Fabric does not log the entire exception though, and that's pretty weird.
