### ISSUE TITLE
Truncated message using filesystem transport

### ISSUE THREAD

**Issue by vegar** [rebus-org/Rebus#826]
I'm experiencing truncated messages using the file system transport. 

```
2019-08-28 10:30:42.543 +02:00 [WRN] An error occurred when attempting to receive the next message: "Newtonsoft.Json.JsonReaderException: Unterminated string. Expected delimiter: \". Path 'Body', line 1, position 4096.
   at Newtonsoft.Json.JsonTextReader.ReadStringIntoBuffer(Char quote) in /_/Src/Newtonsoft.Json/JsonTextReader.cs:line 1119
   at Newtonsoft.Json.JsonTextReader.ReadAsBytes() in /_/Src/Newtonsoft.Json/JsonTextReader.cs:line 521
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter) in /_/Src/Newtonsoft.Json/JsonReader.cs:line 1213
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ResolvePropertyAndCreatorValues(JsonObjectContract contract, JsonProperty containerProperty, JsonReader reader, Type objectType) in /_/Src/Newtonsoft.Json/Serialization/JsonSerializerInternalReader.cs:line 2171
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObjectUsingCreatorWithParameters(JsonReader reader, JsonObjectContract contract, JsonProperty containerProperty, ObjectConstructor`1 creator, String id) in /_/Src/Newtonsoft.Json/Serialization/JsonSerializerInternalReader.cs:line 1943
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue) in /_/Src/Newtonsoft.Json/Serialization/JsonSerializerInternalReader.cs:line 476
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent) in /_/Src/Newtonsoft.Json/Serialization/JsonSerializerInternalReader.cs:line 167
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType) in /_/Src/Newtonsoft.Json/JsonSerializer.cs:line 907
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings) in /_/Src/Newtonsoft.Json/JsonConvert.cs:line 828
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings) in /_/Src/Newtonsoft.Json/JsonConvert.cs:line 786
   at Rebus.Transport.FileSystem.FileSystemTransport.Receive(ITransactionContext context, CancellationToken cancellationToken) in C:\projects-rebus\Rebus\Rebus\Transport\FileSystem\FileSystemTransport.cs:line 109
   at Rebus.Workers.ThreadPoolBased.ThreadPoolWorker.ReceiveTransportMessage(CancellationToken token, ITransactionContext context) in C:\projects-rebus\Rebus\Rebus\Workers\ThreadPoolBased\ThreadPoolWorker.cs:line 136" { SourceContext: "Rebus.Workers.ThreadPoolBased.ThreadPoolWorker" }

```

Inspecting the message shows that it's clearly truncated:

![image](https://user-images.githubusercontent.com/764517/63840689-cd123f00-c981-11e9-87af-717b0c5b93c5.png)

So you have any idea what can cause this?

I'm using Rebus v5.2.1
I have nothing unusual in my configuration

```
config
    .Logging(x => x.Serilog())
    .Serialization(s => s.UseNewtonsoftJson(JsonInteroperabilityMode.PureJson))
    .Routing(cfg =>
    {
        cfg.Register(c => new TypeBasedRouterWithAttributeFallback(c.Get<IRebusLoggerFactory>()));
    })
    .Transport(t =>
    {
        t.UseFileSystem(options.FileSystemPath, options.InputQueue);
    })
    .Subscriptions(cfg =>
    {
        var subscriptionFile = Path.Combine(options.FileSystemPath, "subscriptions." + options.InputQueue + ".json");
        cfg.UseJsonFile(subscriptionFile);
    })
    .Options(o =>
    {
        o.SimpleRetryStrategy(options.ErrorQueue);
        o.EnableIdentityFlowFromIoc(options.SecureAccessToken());
        o.EnableCultureFlow();
        o.EnableCorrelationIdFlow(new CorrelationContextImplementation());
        o.EnableTimeoutExceptionRetryFlow();

        if (options.Audit)
        {
            o.LogPipeline(verbose: true);
            o.EnableMessageAuditing($"{options.InputQueue}.audit");
        }
    })
```

**Comment by mookid8000** [comment]
I have no idea what could have caused that. 

The data is written to each file by [this code](https://github.com/rebus-org/Rebus/blob/master/Rebus/Transport/FileSystem/FileSystemTransport.cs#L74-L81)... 

I guess in theory, something could have interrupted the process while it was writing a message to disk (e.g. by killing the program or something like that), which would have caused only a part of it to have been written..... but I also think that this would be very unlikely.

Have you experienced it before?

Oh, and just out of curiosity: What are you using the file-based transport for?

**Comment by vegar** [comment]
I'm not sure if this has happened before. I sure will be looking for it now, so if it happens again...

We use file-based transport for local development. Service Bus for deployed environments.

**Comment by mookid8000** [comment]
> I'm not sure if this has happened before. I sure will be looking for it now, so if it happens again...

ok, great – please include any details, like e.g. was the prorcess interrupted/killed somehow, or any other thing that might contribute to an explanation

> We use file-based transport for local development. Service Bus for deployed environments.

cool 😄 

did you by any chance have a debugger connected? could the process have been killed? paused?

**Comment by vegar** [comment]
> did you by any chance have a debugger connected? could the process have been killed? paused?

'my' process is in the receiving end of this, so I doubt that was the case. The process sending the message is a asp.net app running in local iis. 

I'm a little surprised that you seem surprised that file-based transport is used. With auditing turned on, it makes for a great experience during development.

**Comment by MrMDavidson** [comment]
Not sure if this is the actual issue... but having a quick look at this I notice a couple of things;
  1. File writes aren't atomic. There's a couple of ways to handle this... but the one that's the simplest and works really easily for NTFS is a file rename (provided source and destination are on the same volume). So instead of;
```
            context.OnCommitted(async () =>
            {
                using (var stream = File.OpenWrite(fullPath))
                using (var writer = new StreamWriter(stream, FavoriteEncoding))
                {
                    await writer.WriteAsync(serializedMessage);
                }
            });
```

Something like;
```
            context.OnCommitted(async () =>
            {
                var shadowFileFullPath = Path.Combine(destinationDirectory, $".shadow.{fileName}");
                using (var stream = File.OpenWrite(shadowFileFullPath ))
                using (var writer = new StreamWriter(stream, FavoriteEncoding))
                {
                    await writer.WriteAsync(serializedMessage);
                }
                File.Move(shadowFileFullPath , fullPath);
            });
```

This way when the receiving process "finds" the file all its contents are definitely in the file.

  2. I notice that @vegar has multiple processes mentioned here. If there's several instances of the application the `_messagesBeingHandled` object won't work effectively. Another option may be to use a global semaphore or a global mutex. The "trick" here is to prefix the mutex/semaphore name with `Global\` to ensure that all processes on the one machine are using the same instance. (See: https://docs.microsoft.com/en-us/windows/win32/api/synchapi/nf-synchapi-createmutexa) So you'd  name the synchronisation object something like `$"Global\\{_inputQueue}-{sha512HashOfFileOnDisksPath}"`. (Reason for taking the hash is there the total name of the synchronisation object has to be less than 260 characters, including the prefix, which makes it shorter than the maximum file path allowed. See: https://msdn.microsoft.com/en-us/library/54wk4yfd(v=vs.110).aspx)

**Comment by mookid8000** [comment]
Ok... I felt like playing around a little, so I made a new version of the file system-based transport 😄 

It uses temp files+rename (as described by @MrMDavidson ) to write messages reliably, and then it uses a clever trick with file locks to acquire exclusive access to messages being received.

With those things in place, the file system transport has suddenly become quite good 🤘 with the file locking trick, it can even be used in "competing consumer" scenarios.

It's out in Rebus 6.0.0-b14

It's a breaking change compared to the v5 file system transport, as it uses a different format for the files on disk. 

The reason this was changed was to allow for

* quickly writing a bunch of files without risking running into conflicts with other writers (a guid in the file name is used to implement that)
* strict ordering of messages sent from one specific sender (a sequence number achieves that)
* _some kind of global ordering_ of messages across all senders (a timestamp in the file name makes that happen)

@vegar if you can upgrade to 6.0.0-b14 and try it, then it would be awesome!
