### ISSUE TITLE
Error while using Rebus 6.0.0 with Rebus.AzureServiceBus 6.0.7

### ISSUE THREAD

**Issue by BadiSatwa** [rebus-org/Rebus#864]
When I'm trying to use libs in that combination I've got exception 
warn: Rebus.Workers.ThreadPoolBased.ThreadPoolWorker[0]
      An error occurred when attempting to receive the next message: System.MissingMethodException: Method not found: 'Void Rebus.Transport.ITransactionContext.OnCompleted(System.Func`1<System.Threading.Tasks.Task>)'.
         at Rebus.AzureServiceBus.AzureServiceBusTransport.Receive(ITransactionContext context, CancellationToken cancellationToken)
         at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
         at Rebus.AzureServiceBus.AzureServiceBusTransport.Receive(ITransactionContext context, CancellationToken cancellationToken)
         at Rebus.Workers.ThreadPoolBased.ThreadPoolWorker.ReceiveTransportMessage(CancellationToken token, ITransactionContext context) in C:\projects-rebus\Rebus\Rebus\Workers\ThreadPoolBased\ThreadPoolWorker.cs:line 148

Regards,
Piotr Balas

**Comment by mookid8000** [comment]
It's because Rebus.AzureServiceBus 6 is not compatible with Rebus 6.

You need to upgrade Rebus.AzureServiceBus to the 7 range, or downgrade Rebus to 5.4
