### ISSUE TITLE
Race Condition when Application is Shutting Down (ASP.NET Core and ServiceProvider)

### ISSUE THREAD

**Issue by arielmoraes** [rebus-org/Rebus#976]
We are using Rebus for our service-to-service communication and in our architecture (using Kubernetes) the services are allowed to scale up and down when necessary and that is very common. 

The problem we are facing is related to the Application Shutting Down and the Rebus stopping the workers, whereas those workers are still processing messages whose handlers have Injected dependecies.

Our logs show exceptions from all the messages being processed after the shutdown has started stating that objects have been Disposed.

We spent a few hours studying the problem and what we could see is the ASP.NET Core disposing the Root Provider before all the work from Rebus is done. We are trying a workaround by hooking the `ApplicationStopping` event and waiting some time for the workers to stop properly, but that feels like a very ugly hack.

As Rebus uses the ThreadPool based worker the ASP.NET Core pipeline is indeed unaware of someone else using the Service Provider services as far as we can see. 

As ASP.NET Core waits for Hosted Services to shutdown before disposing the Root Provider, can maybe a Hosted Service based Worker be a solution for that? Is there a better approach by just hooking the `ApplicationStopping` event?

A important thing to note is that we are using a Scope created inside a custom PipelineStep and not the one created inside the `DepencyInjectionHandlerActivator` as we need to setup some scoped dependencies.

**EDIT**

We've just found out that the problem happens only with injected Singletons.

**EDIT 2**
We are suspecting the order of Disposal is important here, when running on the ASP.NET Core environment we could have a Stop pipeline that runs before the Disposal.

**Comment by arielmoraes** [comment]
We are now testing this workaround:

![image](https://user-images.githubusercontent.com/6741634/122107838-e3f18200-cdf1-11eb-80d3-5745a894baf0.png)

**Comment by mookid8000** [comment]
That's weird! I was actually convinced that this particular thing worked fine.

Previously there was an issue with this, but then [these lines](https://github.com/rebus-org/Rebus.ServiceProvider/blob/master/Rebus.ServiceProvider/ServiceProvider/DependencyInjectionHandlerActivator.cs#L46-L49) were added to help with stopping workers once they start getting `ObjectDisposedException`s from the container.

But once a hander is fully resolved, then it should not be affected by the disposal of the container....

Do you happen to have the full exception details from the logs?

**Comment by arielmoraes** [comment]
These lines will help only if the Handlers have not been activated yet, won't they? In my case the handler was already running as we can see on the log below, the disposed object in that case was the `MemoryCache` used by EntityFramework.

The root cause is the ASP.NET Core disposing the Singletons before Rebus (or its dependecies) finished using them.

```
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'Microsoft.Extensions.Caching.Memory.MemoryCache'.
  at Microsoft.Extensions.Caching.Memory.MemoryCache.CheckDisposed()
  at Microsoft.Extensions.Caching.Memory.MemoryCache.TryGetValue(Object key, Object& result)
  at Microsoft.Extensions.Caching.Memory.CacheExtensions.TryGetValue[TItem](IMemoryCache cache, Object key, TItem& value)
  at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQueryCore[TFunc](Object cacheKey, Func`1 compiler)
  at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
  at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
  at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
  at Remotion.Linq.QueryableBase`1.GetEnumerator()
  at Thunders.BuildingBlocks.IntegrationEvents.Store.IntegrationEventLogStore.MarkEventsAsPublishedAsync(IEnumerable`1 eventsIds, DbTransaction transaction)
  at Thunders.Operations.Infra.Data.OperationContext.SaveEntitiesAsync(CancellationToken cancellationToken) in /src/Thunders.Operations.Infra.Data/OperationContext.cs:line 535
  at Thunders.Operations.Application.IntegrationEventHandlers.Calculator.OperationRecalculatedEventHandler.Handle(OperationRecalculatedEvent message) in /src/Thunders.Operations.Application/IntegrationEventHandlers/Calculator/OperationRecalculatedEventHandler.cs:line 175
  at Rebus.Pipeline.Receive.HandlerInvoker`1.Invoke()
  at Rebus.Pipeline.Receive.DispatchIncomingMessageStep.Process(IncomingStepContext context, Func`1 next)
  at Rebus.Events.Steps.MessageReceivedStep.Process(IncomingStepContext context, Func`1 next)
  at Rebus.Sagas.LoadSagaDataStep.Process(IncomingStepContext context, Func`1 next)
  at Rebus.Pipeline.Receive.ActivateHandlersStep.Process(IncomingStepContext context, Func`1 next)
  at Thunders.Operations.API.Infra.Rebus.ValidateTenantIncomingStep.Process(IncomingStepContext context, Func`1 next) in /src/Thunders.Operations.API/Infra/Rebus/ValidateTenantIncomingStep.cs:line 33
  at Thunders.Operations.API.Infra.Rebus.ValidateTokenIncomingStep.Process(IncomingStepContext context, Func`1 next) in /src/Thunders.Operations.API/Infra/Rebus/ValidateTokenIncomingStep.cs:line 53
  at Rebus.Pipeline.Receive.HandleRoutingSlipsStep.Process(IncomingStepContext context, Func`1 next)
  at Rebus.Retry.Simple.FailedMessageWrapperStep.Process(IncomingStepContext context, Func`1 next)
  at Rebus.Pipeline.Receive.DeserializeIncomingMessageStep.Process(IncomingStepContext context, Func`1 next)
  at Rebus.DataBus.ClaimCheck.HydrateIncomingMessageStep.Process(IncomingStepContext context, Func`1 next)
  at Rebus.Pipeline.Receive.HandleDeferredMessagesStep.Process(IncomingStepContext context, Func`1 next)
  at Thunders.Rebus.ValidateMaxDeferCountStep.Process(IncomingStepContext context, Func`1 next) in /src/Thunders.Operations.API/Infra/Rebus/ValidateMaxDeferCountStep.cs:line 37
  at Rebus.Retry.FailFast.FailFastStep.Process(IncomingStepContext context, Func`1 next)
  at Rebus.Retry.Simple.SimpleRetryStrategyStep.DispatchWithTrackerIdentifier(Func`1 next, String identifierToTrackMessageBy, ITransactionContext transactionContext, String messageId, String secondLevelMessageId)
```

**Comment by arielmoraes** [comment]
One funny thing was that we were migrating an old service to .NET 5 (it was on .NET Core 2.2) and that service was using the IContainerAdapter version, in that class there was a mechanism to dispose the bus similar to what we've implemented to solve the problem. I couldn't find the example we used a few years ago but the constructor registers the dispose as a Application Stopping event as shown below.

```csharp
/// <summary>
/// Initializes a new instance of the <see cref="ThundersContainerAdapter"/> class.
/// </summary>
/// <param name="provider">The service provider used to yield handler instances.</param>
public ThundersContainerAdapter(IServiceProvider provider)
{
    _provider = provider ?? throw new ArgumentNullException(nameof(provider));

    var applicationLifetime = _provider.GetService<IApplicationLifetime>();
    applicationLifetime?.ApplicationStopping.Register(Dispose);
}
```

**Comment by mookid8000** [comment]
Yeah ok I think I understand the problem now. The reason this was removed, was to avoid the dependency on Microsoft.AspNetCore.Hosting.Abstractions.

![image](https://user-images.githubusercontent.com/32968/123593116-72043a00-d7ee-11eb-8c84-dfda7c89a442.png)

Do you know of any alternative way of detecting that the service provider is about to be disposed?

**Comment by mookid8000** [comment]
I've now tried replacing the dependency on Microsoft.Extensions.DependencyInjection by Microsoft.Extensions.Hosting.Abstractions, and then added a small `BusStop` (😁 ) background service that disposes the bus.

In my tests it seemed to work fine, although there is a small thing to watch out for: If other background services depend on the bus to do their work, and they need to use the bus when the host is shutting down, then they must be registered in the container BEFORE Rebus is added – otherwise, the bus will have been disposed when they get their stop methods called.

The background service `BackgroundServiceExample` illustrates this point.

It's out as Rebus.ServiceProvider 7.0.0-b2 on NuGet.org now 🙂 please give it a spin and see if it works, and then I'll release a properly versioned package.

**Comment by dimkadv2** [comment]
Hi
After starting the application, I did post post:

```c#

await bus.Publish(new SetControllerVariableMessage());

```

the handler looks like this:

```c#

    public class SetControllerVariableMessageHandler : IHandleMessages<SetControllerVariableMessage>
    {
        public Task Handle(SetControllerVariableMessage message)
        {
            System.Console.WriteLine("Hello world");

            return Task.CompletedTask;
        }
    }

```

When I run the application, I see the following in the console:

```
[DBG] Rebus.Pipeline.Receive.DispatchIncomingMessageStep (Thread #10): Dispatching "Rbu.API.Services.Messages.RequestWorkTableMessage, Rbu.API.Services" "e8b67dfa-069b-4c39-b881-eb533a0311ae" to 2 handlers took 19 ms
[INF] Rebus.Transport.InMem.InMemNetwork (Rebus 1 worker 1): queue ---> b063e7d0-a877-4182-aaef-a80f6640225a (In-mem network 2)
Hello world
Hello world
[DBG] Rebus.Pipeline.Receive.DispatchIncomingMessageStep (Rebus 1 worker 1): Dispatching "Rbu.API.Services.Messages.SetControllerVariableMessage, Rbu.API.Services" "b063e7d0-a877-4182-aaef-a80f6640225a" to 2 handlers took 1 ms
```


it turns out that the message from the queue was received twice

**Comment by mookid8000** [comment]
@arielmoraes Have you had a chance to try it?

**Comment by arielmoraes** [comment]
@mookid8000 sorry for the long delay, I was extremely busy. 

Using the Background Service is the way to go. That was the solution we adopted to fix the issue before the PR.

Thank you. Closing the issue.
