### ISSUE TITLE
Saga exception using mssql

### ISSUE THREAD

**Issue by yg2522** [rebus-org/Rebus#984]
I have a test solution going using mssql to store the saga data and simpleinjector for IoC.  the setup has two publishers that will each publish correlated messages that the saga subscribes to and processes.  The problem is that if the messages come in at exactly the same time, I get an exception.  The logs reads like this:

[DBG] Rebus.Sagas.LoadSagaDataStep (Thread #8): Created new saga data with ID df6008b4-dd43-4aa0-882d-447ef24be868 for message "Process1Complete/3a22fa6e-88c7-4d04-8a94-826f24a0fa90"
[DBG] Rebus.Sagas.LoadSagaDataStep (Thread #6): Created new saga data with ID 57f6f8d8-cd93-4fe1-96e7-94e2e05436e8 for message "Process2Complete/5cf11675-ea3d-4b0d-bd1b-c934b9821769"
Pre Saga Check: df6008b4-dd43-4aa0-882d-447ef24be868
Pre Saga Check: 57f6f8d8-cd93-4fe1-96e7-94e2e05436e8
[DBG] Rebus.Pipeline.Send.SendOutgoingMessageStep (Thread #8): Sending RebusFinishProcess.VerifyComplete -> "##### MagicExternalTimeoutManagerAddress #####"
[DBG] Rebus.Pipeline.Send.SendOutgoingMessageStep (Thread #6): Sending RebusFinishProcess.VerifyComplete -> "##### MagicExternalTimeoutManagerAddress #####"
Process2Complete received: 16d2ff3b-8104-4bde-9164-9af0b6d8ac74
Process1Complete received: 16d2ff3b-8104-4bde-9164-9af0b6d8ac74
[DBG] Rebus.Pipeline.Receive.DispatchIncomingMessageStep (Thread #5): Dispatching "RebusCore.Process2Complete, RebusCore" "5cf11675-ea3d-4b0d-bd1b-c934b9821769" to 1 handlers took 66 ms
[DBG] Rebus.Pipeline.Receive.DispatchIncomingMessageStep (Thread #11): Dispatching "RebusCore.Process1Complete, RebusCore" "3a22fa6e-88c7-4d04-8a94-826f24a0fa90" to 1 handlers took 67 ms
[WRN] Rebus.Retry.ErrorTracking.InMemErrorTracker (Thread #6): Unhandled exception 1 while handling message with ID "5cf11675-ea3d-4b0d-bd1b-c934b9821769"
Rebus.Exceptions.ConcurrencyException: Could not update index for saga with ID 57f6f8d8-cd93-4fe1-96e7-94e2e05436e8 because of a PK violation - there must already exist a saga instance that uses one of the following correlation properties: ProcessId='16d2ff3b-8104-4bde-9164-9af0b6d8ac74'
   at Rebus.SqlServer.Sagas.SqlServerSagaStorage.<CreateIndex>d__23.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Rebus.SqlServer.Sagas.SqlServerSagaStorage.<Insert>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Rebus.Sagas.LoadSagaDataStep.<SaveSagaData>d__10.MoveNext() in C:\projects-rebus\Rebus\Rebus\Sagas\LoadSagaDataStep.cs:line 203
--- End of stack trace from previous location where exception was thrown ---
   at Rebus.Sagas.LoadSagaDataStep.<SaveSagaData>d__10.MoveNext() in C:\projects-rebus\Rebus\Rebus\Sagas\LoadSagaDataStep.cs:line 217
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Rebus.Sagas.LoadSagaDataStep.<Process>d__7.MoveNext() in C:\projects-rebus\Rebus\Rebus\Sagas\LoadSagaDataStep.cs:line 101
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Rebus.Pipeline.Receive.ActivateHandlersStep.<Process>d__3.MoveNext() in C:\projects-rebus\Rebus\Rebus\Pipeline\Receive\ActivateHandlersStep.cs:line 47
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Rebus.Pipeline.Receive.HandleRoutingSlipsStep.<Process>d__3.MoveNext() in C:\projects-rebus\Rebus\Rebus\Pipeline\Receive\HandleRoutingSlipsStep.cs:line 40
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Rebus.Pipeline.Receive.DeserializeIncomingMessageStep.<Process>d__2.MoveNext() in C:\projects-rebus\Rebus\Rebus\Pipeline\Receive\DeserializeIncomingMessageStep.cs:line 34
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Rebus.DataBus.ClaimCheck.HydrateIncomingMessageStep.<Process>d__2.MoveNext() in C:\projects-rebus\Rebus\Rebus\DataBus\ClaimCheck\HydrateIncomingMessageStep.cs:line 51
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Rebus.Retry.FailFast.FailFastStep.<Process>d__5.MoveNext() in C:\projects-rebus\Rebus\Rebus\Retry\FailFast\FailFastStep.cs:line 71
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Rebus.Retry.Simple.SimpleRetryStrategyStep.<DispatchWithTrackerIdentifier>d__10.MoveNext() in C:\projects-rebus\Rebus\Rebus\Retry\Simple\SimpleRetryStrategyStep.cs:line 121
[DBG] Rebus.Sagas.LoadSagaDataStep (Thread #12): Found existing saga data with ID df6008b4-dd43-4aa0-882d-447ef24be868 for message "Process2Complete/5cf11675-ea3d-4b0d-bd1b-c934b9821769"
Process2Complete recieved: 16d2ff3b-8104-4bde-9164-9af0b6d8ac74
Post Saga Complete: df6008b4-dd43-4aa0-882d-447ef24be868
[DBG] Rebus.Pipeline.Send.SendOutgoingMessageStep (Thread #8): Sending RebusCore.Complete -> "<no destinations>"
[DBG] Rebus.Pipeline.Receive.DispatchIncomingMessageStep (Thread #8): Dispatching "RebusCore.Process2Complete, RebusCore" "5cf11675-ea3d-4b0d-bd1b-c934b9821769" to 1 handlers took 18 ms

Basically both Process1Complete and Process2Complete are received at the same time and eventually tries to update the saga table simultaneously because both processes are being worked on at the same time.  The saga apparently does get marked for completion appropriately.  Also if I delay sending one of the messages, the exception doesn't show up as expected, so I just want to ensure that the exception is expected behavior when you simultaneously process messages that are correlated.  The saga setup is pretty basic since I wanted to just test how things are getting handled:

    public class RebusSaga : Saga<RebusSagaData>, IAmInitiatedBy<Process1Complete>, IAmInitiatedBy<Process2Complete>, IHandleMessages<VerifyComplete>
    {
        private IBus Bus { get; set; }
        public RebusSaga(IBus bus)
        {
            Bus = bus;
        }
        public async Task Handle(Process1Complete message)
        {
            await Pre();
            Console.WriteLine($"Process1Complete received: {message.Id}");
            Data.Process1Complete = true;

            await Post();
        }

        public async Task Handle(Process2Complete message)
        {
            await Pre();
            Console.WriteLine($"Process2Complete received: {message.Id}");
            Data.Process2Complete = true;
            await Post();
        }

        public async Task Handle(VerifyComplete message)
        {
            Console.WriteLine($"The saga for id {message.Id} was not completed within 20s timeout");

            await Bus.Publish(new NotComplete(message.Id));

            MarkAsComplete();
        }

        protected override void CorrelateMessages(ICorrelationConfig<RebusSagaData> config)
        {
            config.Correlate<Process1Complete>(p1 => p1.Id, d => d.ProcessId);
            config.Correlate<Process2Complete>(p2 => p2.Id, d => d.ProcessId);

            // internal verification message
            config.Correlate<VerifyComplete>(m => m.Id, d => d.ProcessId);
        }

        async Task Pre()
        {
            if (!IsNew) return;

            Console.WriteLine($"Pre Saga Check: {Data.Id}");

            await Bus.DeferLocal(TimeSpan.FromSeconds(20), new VerifyComplete(Data.Id));

        }

        async Task Post()
        {
            if (!Data.Complete) return;

            Console.WriteLine($"Post Saga Complete: {Data.Id}");

            await Bus.Publish(new Complete(Data.Id));

            MarkAsComplete();
        }
    }

**Comment by mookid8000** [comment]
The exception is expected behavior when there's contention around a specific saga data instance. 🙂
